### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by steveneal** [mapbox/mapbox-maps-flutter#105]
Hi, not sure where else I can ask this so I hope this is an appropriate question here.

Can you tell me whether there are plans to implement offline map support? And if so what is the planned timeline? 

I'd like to adop the use of this official flutter package, but cannot as offline map access is a critical requirement for our app.

Thanks.

**Comment by steveneal** [comment]
Hi - great to see this has been assigned. Thanks.

Any idea what timeline is likely please?

Is it worth holding the release of our new app for this to be included?

**Comment by arkeri** [comment]
Has this feature/package been deprioritized? We're waiting on it to switch from the other version.

**Comment by keithgulbro** [comment]
@yunikkk Just checking in to see if this is in active development or has been prioritized. It seems a decent chunk of developers would find significant use from this feature enhancement. ❤️

**Comment by aardrop** [comment]
Any update on this?

**Comment by aloh86** [comment]
Really need to support offline maps in my app....please let us know what is going on with this.

**Comment by aloh86** [comment]
I found this: https://medium.com/@jamesayvaz/offline-maps-for-your-flutter-app-3ea64111b73c
Not sure if it's still applicable with the most recent SDK, but I'm going to give it a try.

**Comment by wasdee** [comment]
> I found this: [medium.com/@jamesayvaz/offline-maps-for-your-flutter-app-3ea64111b73c](https://medium.com/@jamesayvaz/offline-maps-for-your-flutter-app-3ea64111b73c) Not sure if it's still applicable with the most recent SDK, but I'm going to give it a try.

how was it? is it a success?

**Comment by up4154** [comment]
> > I found this: [medium.com/@jamesayvaz/offline-maps-for-your-flutter-app-3ea64111b73c](https://medium.com/@jamesayvaz/offline-maps-for-your-flutter-app-3ea64111b73c) Not sure if it's still applicable with the most recent SDK, but I'm going to give it a try.
> 
> how was it? is it a success?



> I found this: https://medium.com/@jamesayvaz/offline-maps-for-your-flutter-app-3ea64111b73c Not sure if it's still applicable with the most recent SDK, but I'm going to give it a try.

but the issue with this is, it only support offline for styles not for tiles or layers

**Comment by matejthetree** [comment]
Also interested in offline support. Ready to help with development if there can be guidance from someone on the team

**Comment by ventskus-roman** [comment]
Is there any progress on this feature?

**Comment by silentlight** [comment]
Any idea if this will be implemented. We maintain our binding but it is not ideal.

**Comment by steveneal** [comment]
@yunikkk can you respond to the questions above please? 

Is an offline maps feature, where map tiles can be downloaded from Mapbox, likely to be implemented in this project any time soon? 

Thanks.

**Comment by yunikkk** [comment]
> @yunikkk can you respond to the questions above please?
> 
> Is an offline maps feature, where map tiles can be downloaded from Mapbox, likely to be implemented in this project any time soon?
> 
> Thanks.

@steveneal hey, unfortunately I can't say the priority or ETA of the offline support, busy with other stuff at the moment. @baleboy @evil159 do you folks have an idea?

**Comment by baleboy** [comment]
I answered the following to @steveneal on Discord:

"Hi @Steve Neal, thank you for the question. Offline support is at the top of our priority list once the current feature set is considered done. However unfortunately we are not able to give a timeline at this point."

**Comment by ravitejaavv** [comment]
Hello,
Is there any update on this?

**Comment by up4154** [comment]
I have  made a  custom wrapper in kotlin and java to support this functionality few months back and it was support the offline functionality

**Comment by TheRedSpy15** [comment]
We should try to concentrate this discussion on the original issue #11

**Comment by maios** [comment]
Hi all, we have now added first support for offline map and it is planned for MapboxMaps Flutter v2.1.0 as commented in the original issue https://github.com/mapbox/mapbox-maps-flutter/issues/11#issuecomment-2165193767. I will close this now and keep the original issue for easier tracking.
