### ISSUE TITLE
LocationPuck2d does not rotate according to bearing.

### ISSUE THREAD

**Issue by serraojoao** [mapbox/mapbox-maps-flutter#120]
When using "showAccuracyRing" the locationPuck2d does not rotate according to bearing.

does NOT work, custom location puck does not rotate:
_mapController?.location
        .updateSettings(LocationComponentSettings(enabled: true, showAccuracyRing: true, puckBearingEnabled: true, locationPuck:
    LocationPuck(locationPuck2D: LocationPuck2D(topImage: list,),),) );
    
    
works as expected, custom location puck rotates to bearing direction:
_mapController?.location
        .updateSettings(LocationComponentSettings(enabled: true, puckBearingEnabled: true, locationPuck:
    LocationPuck(locationPuck2D: LocationPuck2D(topImage: list,),),) );

**Comment by maios** [comment]
I'm closing this issue now, please reopen if you still experience this with our latest release. Thank you :)
