### ISSUE TITLE
Remove Watermark

### ISSUE THREAD

**Issue by marcoabat** [mapbox/mapbox-maps-flutter#132]
How can I remove the Mapbox Watermark in the bottom left corner and the scale UI ?
<img height="30%" width="30%" alt="Shows an illustrated sun in light mode and a moon with stars in dark mode." src="https://user-images.githubusercontent.com/112637173/228823191-083efa33-42f2-45c2-abc9-fb996a67081c.png">

**Comment by markpeterfejes** [comment]
Unfortunately (and partly understandably) Mapbox does not provide a plan (Free or paid) where the attribution can be removed. We must include the Mapbox logo if we use the product. 

Read about what's possible here: https://docs.mapbox.com/help/getting-started/attribution/
