### ISSUE TITLE
How to set zindex order between Point and Line

### ISSUE THREAD

**Issue by vanvixi** [mapbox/mapbox-maps-flutter#144]
I'm having an issue where Lines are superimposed on Points. Is there a way to do the reverse?

![mapbox](https://user-images.githubusercontent.com/75975945/232398680-39871724-0036-4bac-a8cb-2edbdc95c081.png)

**Comment by ezesoftchao** [comment]
same issue

**Comment by geisterfurz007** [comment]
Possible dupe: #37

**Comment by ezesoftchao** [comment]
> I'm having an issue where Lines are superimposed on Points. Is there a way to do the reverse?
> 
> ![mapbox](https://user-images.githubusercontent.com/75975945/232398680-39871724-0036-4bac-a8cb-2edbdc95c081.png)

https://github.com/mapbox/mapbox-maps-flutter/issues/37#issuecomment-1416251645

**Comment by vanvixi** [comment]
I close this issue because it was resolved here:
https://github.com/mapbox/mapbox-maps-flutter/issues/37#issuecomment-1416251645
