### ISSUE TITLE
[Ugrent] Flutter 3.7.12 cant render MapWidget on Android 

### ISSUE THREAD

**Issue by figureai** [mapbox/mapbox-maps-flutter#149]
Flutter 3.7.12 cant render MapWidget on Android, but it is normal on Flutter 3.0.4 versions and iOS
The error message is as follows,Does anyone know how to fix it？

I/Mbgl-FontUtils( 2592): Couldn't map font family for local ideograph, using sans-serif instead
E/ThemeUtils( 2592): View class com.mapbox.maps.plugin.compass.CompassViewImpl is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
E/ThemeUtils( 2592): View class com.mapbox.maps.plugin.logo.LogoViewImpl is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
E/ThemeUtils( 2592): View class com.mapbox.maps.plugin.attribution.AttributionViewImpl is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
I/Mapbox  ( 2592): [maps-android\MapController]: Add MAPBOX_LIFECYCLE_PLUGIN_ID plugin dependency to the classpath take automatically load the plugin implementation.
I/PlatformViewsController( 2592): Hosting view in view hierarchy for platform view: 1
I/BufferQueueConsumer( 2592): [](id:a2000000004,api:0,p:-1,c:2592) connect: controlledByApp=true
D/Surface ( 2592): lockHardwareCanvas
I/BufferQueueProducer( 2592): [SurfaceTexture-0-2592-2](id:a2000000004,api:1,p:2592,c:2592) connect: api=1 producerControlledByApp=true
E/FrameEvents( 2592): updateAcquireFence: Did not find frame.
D/Surface ( 2592): lockHardwareCanvas
D/TextureView( 2592): getHardwareLayer, createNewSurface:true
I/BufferQueueConsumer( 2592): [](id:a2000000005,api:0,p:-1,c:2592) connect: controlledByApp=true
D/libMEOW ( 2592): meow new tls: 0xb4000077be730d00
D/libMEOW ( 2592): applied 1 plugins for [com.mddoscar.velotricbike]:
D/libMEOW ( 2592):   plugin 1: [libMEOW_gift.so]:
2
I/Mapbox  ( 2592): [maps-android\Mbgl-EGLConfigChooser]: In emulator: false
I/Mapbox  ( 2592): [maps-android\Mbgl-EglCore]: EGLContext created, client version 2
I/BufferQueueProducer( 2592): [SurfaceTexture-0-2592-3](id:a2000000005,api:1,p:2592,c:2592) connect: api=1 producerControlledByApp=true
I/Mapbox  ( 2592): [maps-core]: Using OpenGL render backend
E/FrameEvents( 2592): updateAcquireFence: Did not find frame.

**Comment by figureai** [comment]
I compared the running logs under normal conditions and found that the following error occurred under version 3.7.12, but I don't know how to solve it
`Hosting view in view hierarchy for platform view: 1  `

**Comment by yunikkk** [comment]
@figureai I've updated flutter installation to 3.7.12 but demo app keeps working on Android for me. Could you share more info on your setup e.g. device/os used, `flutter doctor` output, code that fails?

**Comment by figureai** [comment]
I solve it just update the mapbox-maps-flutter to latest, thanks every.
