### ISSUE TITLE
`toScreenLocation()` function support

### ISSUE THREAD

**Issue by YumNumm** [mapbox/mapbox-maps-flutter#15]
Hi, I love this plugin and I want to say thank you!

I am looking to implement `toScreenLocation()` function which is in mapbox-gl.
**With this function, you can convert latitude and longitude coordinates to screen coordinates.**

```dart
/// Returns the point on the screen that corresponds to a geographical coordinate ([latLng]). The screen location is in screen pixels (not display pixels) relative to the top left of the map (not of the whole screen)
  ///
  /// Note: The resulting x and y coordinates are rounded to [int] on web, on other platforms they may differ very slightly (in the range of about 10^-10) from the actual nearest screen coordinate.
  /// You therefore might want to round them appropriately, depending on your use case.
  ///
  /// Returns null if [latLng] is not currently visible on the map.
  Future<Point> toScreenLocation(LatLng latLng) async {
    return _mapboxGlPlatform.toScreenLocation(latLng);
  }
```
FROM: https://github.com/flutter-mapbox-gl/maps/blob/f505fcf5c79b75c165703028af77f3af62d382ae/lib/src/controller.dart#L1211-L1219

**Comment by LjubiTech-Maxko** [comment]
This functionality is already implemented.

https://github.com/mapbox/mapbox-maps-flutter/blob/6e83a2baf7121e9680f71da1185ec96a889694a0/lib/src/mapbox_map.dart#L279-L286

**Comment by YumNumm** [comment]
Oh thanks! 
I overlooked this.
