### ISSUE TITLE
Exception has occurred _CastError (type '_Map<Object?, Object?>' is not a subtype of type 'Map<String?, Object?>?' in type cast)Exception has occurred

### ISSUE THREAD

**Issue by AAverin1994** [mapbox/mapbox-maps-flutter#150]
Hello. I have found an issue which is blocker for my current solution. 
I am using FeatureExtensionValue for taking featureCollection and trying to remap it
![image](https://user-images.githubusercontent.com/11915333/234835693-97e42dc7-7db6-4908-8297-2841e85878c9.png)

@sbma44 @RennanAgroSmart @yunikkk @LjubiTech-Maxko Could you please help me? 
As I see, one person had already fount this issue and fixed it https://github.com/mapbox/mapbox-maps-flutter/pull/84/files but PR is closed for some reason.

Version: 0.4.2

Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (9 days ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1

**Comment by evil159** [comment]
Should be fixed in https://github.com/mapbox/mapbox-maps-flutter/pull/249
