### ISSUE TITLE
Map Screen is Blank while launching app with mapbox implemetation

### ISSUE THREAD

**Issue by vaibhavvk18** [mapbox/mapbox-maps-flutter#159]
ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Please ensure that the hosting activity/fragment is a valid LifecycleOwner

<img width="1440" alt="Screenshot 2023-05-10 at 12 40 21 AM" src="https://github.com/mapbox/mapbox-maps-flutter/assets/126235226/e83bc851-bc72-4436-8c0b-6ec0d1e3f850">

**Comment by anton-yarish** [comment]
How did you fix this?
