### ISSUE TITLE
how to customize markers in map

### ISSUE THREAD

**Issue by Sang-Nguyen-Sunny** [mapbox/mapbox-maps-flutter#16]
I'm using the latest version of the library, but didn't find a way to customize the marker in a particular way, currently it just adjusts to the built-in method which is difficult to customize again.

**Comment by serraojoao** [comment]
you can use an image your assets folder to set "image" parameter in "PointAnnotationOptions", before you need to convert it to Uint8List

**Comment by yunikkk** [comment]
@Sang-Nguyen-Sunny markers could be customized using very similar APIs to the Android/iOS platforms, have you tried those described at https://github.com/mapbox/mapbox-maps-flutter#markers-and-annotations?
