### ISSUE TITLE
SDK Registry token is null.

### ISSUE THREAD

**Issue by renatoacc** [mapbox/mapbox-maps-flutter#178]
For a few weeks I have been having one problem with my app, I try to build the app to test, and gives me this error. 

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/home/xxxxxxxx/.pub-cache/hosted/pub.dev/mapbox_maps_flutter-0.4.3/android/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating project ':mapbox_maps_flutter'.
> SDK Registry token is null. See README.md for more information.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* Where:
Script '/home/xxxxxxxxx/fvm/versions/3.7.6/packages/flutter_tools/gradle/flutter.gradle' line: 407

* What went wrong:
A problem occurred configuring project ':mapbox_maps_flutter'.
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':mapbox_maps_flutter' of type org.gradle.api.Project.
   > Could not find method implementation() for arguments [project ':flutter_plugin_android_lifecycle'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
   > Could not get unknown property 'android' for project ':mapbox_maps_flutter' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Exception: Gradle task assembleDebug failed with exit code 1

I see the same issue on mapbox_gl. 
I use the Android studio version electric eel IDE, but I start to have this problem when I update my IDE to the Flamingo version, I downgrade and I can work for one or two hours, and now gives me the same error. 

Can you help me?

**Comment by renatoacc** [comment]
To solve this problem, e 14 hours later my team leader tell me to try to do the key export inside the project folder and BUM the app runs perfectly. Before I tried to do the export in the main folder and run the app and nothing,

**Comment by navirobayo** [comment]
I'm commenting in case someone else had the same issue. The answer is very simple once you realize it: 

You need to create the **_gradle.properties_** in your actual hard drive , not in the project folder. 

The mapbox documentation is very clear about this [here](https://docs.mapbox.com/android/maps/guides/install/#configure-your-secret-token) but for some reason we might ignore it. 


Hope it helps, cheers.
