### ISSUE TITLE
Memory leak on iOS

### ISSUE THREAD

**Issue by OneupLee** [mapbox/mapbox-maps-flutter#189]
I wrote a simple page with only one mapbox in it. When I repeatedly opened and closed the page, I manually GCed it and found that there were several MapBox instances in memory. Repeat until the app crashes.
<img width="929" alt="image" src="https://github.com/mapbox/mapbox-maps-flutter/assets/32166473/10f12ed7-ff8a-4175-aafa-dc1f9ad289c3">
I saw that version 0.4.3 fixed the memory leak problem, but I found that there is no memory leak on Android, and there is still a memory leak problem on iOS. The same goes for version 0.4.4.

test on iPhone 12 pro max, iOS 16.5, Samsung S20 Android13

flutter doctor
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.3 22E252 darwin-arm64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

<img width="915" alt="image" src="https://github.com/mapbox/mapbox-maps-flutter/assets/32166473/6d83c2af-3981-4f6a-ab8b-0a8d60cc6978">
<img width="944" alt="image" src="https://github.com/mapbox/mapbox-maps-flutter/assets/32166473/a75225bc-3e6f-4807-a196-e3c2b294533c">
<img width="918" alt="image" src="https://github.com/mapbox/mapbox-maps-flutter/assets/32166473/5487f205-4c12-41b6-badd-ea2c8c6f5d87">
![image](https://github.com/mapbox/mapbox-maps-flutter/assets/32166473/7736679c-c4cf-40b0-b16c-934157559e21)

**Comment by OneupLee** [comment]
somebody help

**Comment by OneupLee** [comment]
update:
example app has the same problem, especially "Full screen map"

**Comment by kamami** [comment]
Any feedback?

**Comment by favazHF** [comment]
Any update??

**Comment by OneupLee** [comment]
HI everyone! This problem seems to have been resolved by the Flutter team. I tested on 3.12.0-4.0.pre.39 and found no memory leaks. Maybe I can close this issue later.

```shell
[✓] Flutter (Channel master, 3.12.0-4.0.pre.39, on macOS 13.3 22E252
    darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.12.0-4.0.pre.39 on channel master at
      /Users/mac/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • FLUTTER_GIT_URL = https://github.com/flutter/flutter.git
    • Framework revision 4f94dee851 (3 days ago), 2023-06-12 01:57:26 -0400
    • Engine revision effea50196
    • Dart version 3.1.0 (build 3.1.0-197.0.dev)
    • DevTools version 2.24.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Users/mac/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.1012163
      9/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/mac/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.1012163
      9/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/mac/Applications/JetBrains Toolbox/IntelliJ IDEA
      Ultimate.app
    • Flutter plugin version 73.1.1
    • Dart plugin version 231.9065

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/mac/Library/Application
      Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9011.34/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • Oneup的iPhone (mobile) • 00008101-001574D23EE1001E • ios            • iOS
      16.5 20F66
    • macOS (desktop)       • macos                     • darwin-arm64   • macOS
      13.3 22E252 darwin-arm64
    • Chrome (web)          • chrome                    • web-javascript •
      Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by yunikkk** [comment]
@OneupLee I was able to check the leak and it indeed reproduces on my end as well with Flutter 3.7.12. 
I've digged a bit and it seems the root cause is the https://github.com/flutter/flutter/pull/124066. I've applied same fix clearing focus nodes and leak goes away with older flutter as well.

@abduraimbekyarkinov haven't yet checked with newer Flutter myself though if I'm correct about the leak cause - commit with the fix https://github.com/flutter/flutter/commit/d1b8527f6b312a365cd708d1f2a5c5de645548eb is present in 3.10.0+.

**Comment by OneupLee** [comment]
@yunikkk @abduraimbekyarkinov Thanks Reply. I tested on the latest stable version 3.10.6 and found no memory leaks. So I will close this issue. But the crash due to [#127489](https://github.com/flutter/flutter/issues/127489) persists, it's a Flutter issue.
