### ISSUE TITLE
Filter the data of layer

### ISSUE THREAD

**Issue by fatalcaron** [mapbox/mapbox-maps-flutter#19]
We want to show a selection on the map. With Mapbox  GL JS we had different strategies to achieve this. Filter the source data or update the source to represent the selected data.

I don't see how we can represent a selection. 

See this example with the filter strategy:
https://docs.mapbox.com/mapbox-gl-js/example/using-box-queryrenderedfeatures/

See this example for the setData method on the source. This could be usefull for multiple scenario like show realtime data
https://docs.mapbox.com/mapbox-gl-js/example/live-update-feature/
`map.getSource('trace').setData(data);`

**Comment by fatalcaron** [comment]
Just find out how, to update a GeojsonSource.
```
GeoJsonSource source = await map.style.getSource(_selectionSourceId) as GeoJsonSource;
await source.updateGeoJSON(json.encode(data));
```

But it will still be usefull to filter the data of a layer

**Comment by LjubiTech-Maxko** [comment]
For the second example of updating data dynamically for already added source you could use something like this, assuming we are using GeoJsonSource and data variable representing encoded valid geojson:

```
final GeoJsonSource source = await mapboxMap.style.getSource('source_id') as GeoJsonSource;
source.updateGeoJSON(data);
```

**Comment by yunikkk** [comment]
@fatalcaron you could use `mapboxMap.style.setStyleLayerProperty("layer-id", "filter", '...');` to set filter to level

**Comment by fatalcaron** [comment]
Ok thanks, so we can use all the native property through `setStyleLayerProperty` method but not all the properties are exposed through layer configuration.
I close this issue! Thanks again

**Comment by kamami** [comment]
How can I reset the filter again? 
This is my filter:  `mapboxMap?.style.setStyleLayerProperty("unclustered-point", "filter", '["==", "fastCharger", true]');`

**Comment by kamami** [comment]
Any idea?
