### ISSUE TITLE
Set authorization token for tile source requests

### ISSUE THREAD

**Issue by arctouch-BrunoFerrari** [mapbox/mapbox-maps-flutter#202]
Hey all, I'm currently using the aloft.ai with mapbox, and I need to include the tiles to be displayed on the map, but the API requires that the requests carry a token with them, such as at [this example](https://github.com/Kittyhawkio/tile-server-demo/blob/main/mapbox-demo.html) where mapbox provides the `transformRequest` parameter and you can include headers.

Is there anything similar on this SDK to include additional headers to these requests? I was looking for something similar in the codebase but haven't found it.

If it doesn't provide support, could I make these requests on my application and send the data to mapbox somehow?

**Comment by srmncnk** [comment]
Unavailable. Even with 9.X there was only a workaround for implementing a custom http interceptor on Android and use swizzling to do the same on iOS.

You're better of passing the tokens as query parameters.

**Comment by arctouch-BrunoFerrari** [comment]
@srmncnk Thanks for the answer, I'm currently using a query parameter to authorize the requests. However, some requests done internally on mapbox are still unauthorized because I don't have control over the URL. 

Am I doing something wrong? Is it supposed to work just by injecting the key when I'm adding the sources?

For example, I could check that the tiles URL (`"https://maps.aloft.ai/faa_airspace/{z}/{x}/{y}"`) doesn't work without authentication, and it's being made internally, so I don't have access to the URL itself.

**Comment by srmncnk** [comment]
@arctouch-BrunoFerrari How about if you use
```
"https://maps.aloft.ai/faa_airspace/{z}/{x}/{y}?access_token={your_access_token}"
```
And change the source whenever access token is invalidated?

**Comment by arctouch-BrunoFerrari** [comment]
@srmncnk I've tried, but this URL comes from one of the source requests made internally by the mapbox, and I don't have control over the URL to change it. Do you know if there's a way to make it manually and then set to mapbox or another alternative that could help with this?

**Comment by arctouch-felipecastilhos** [comment]
I’m working on the same project as Bruno. I’m not sure what the “styles.json” you’re asking about is.
Maybe we can clarify things by sharing some code:
This is how we’re adding the data source. In our current code, we’re populating these values from a previous request we made to the Aloft API.
Here’s an example of how we add a value to the source:

```
_controller?.style.addSource(
  VectorSource(
    id: 'real_time',
    url: 'https://maps.aloft.ai/real_time?pk=[private_key]',
  ),
);
```

After adding the data source, we’re trying to add a layer to it:
```
for (final layer in layers) {
  widget.logger.d('Layer: $layer');
  final sourceId = layer['source'];
  final layerId = layer['id'];
  final layerType = layer['type'];

  switch (layerType) {
    case 'line':
      _controller?.style.addLayer(
        LineLayer(
          id: layerId,
          sourceId: sourceId,
          lineCap: LineCap.ROUND,
          lineJoin: LineJoin.ROUND,
        ),
      );
      break;
    case 'fill':
      _controller?.style.addLayer(
        FillLayer(
          id: layerId,
          sourceId: sourceId,
        ),
      );
      break;
  }

  widget.logger.d('Added layer: [$layerId], [$sourceId], [$layerType]');
}
```
Here’s an example of what the returned URL of the added source looks like:
```
{
  "tilejson": "3.0.0",
  "tiles": ["https://maps.aloft.ai/real_time/{z}/{x}/{y}"],
  "vector_layers": [{
    "id": "tiles.faa_tfrs",
    "fields": {
      "days_of_week": "varchar",
      "ends_at": "timestamp",
      "starts_at": "timestamp",
      "text": "text",
      "tfr_id": "varchar",
      "id": "int8",
      "link": "varchar",
      "reason": "varchar"
    }
  }],
  "bounds": [0, 0, 0],
  "description": "tiles.faa_tfrs.geom",
  "name": "tiles.faa_tfrs"
}
```
`
We suspect that we’re receiving a 401 response code when the library calls the URL specified in those tiles in the response because we don't have/don't know how to add the private key in the header or with query params.

**Comment by srmncnk** [comment]
@arctouch-felipecastilhos @arctouch-BrunoFerrari This is a bit out of scope regarding the flutter wrapper.

You use "url" argument in VectorSource which requests a tilejson format, where it expects "tiles" to point to a TMS resource.
Instead use "tiles" argument directly in VectorSource, so you can skip one step and request tiles directly.

Docs: https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/

**Comment by arctouch-felipecastilhos** [comment]
@srmncnk I did work. Thank you.

I don't know if it's just my personal opinion here, but those parameters could be split into two different interfaces. Setting up the url, and the TMS resource and they can override each other it was very confusing. 

But thanks again. and I really appreciate your fast replies. 🫂

**Comment by srmncnk** [comment]
👍

Agreed on the API issue. I'm not associated with Mapbox, just another user, so I see your point very clearly.

**Comment by arctouch-BrunoFerrari** [comment]
I just came to thank you as well @srmncnk, as @arctouch-felipecastilhos said, we've managed to sort it out. :)
