### ISSUE TITLE
How Can I remove the logoView

### ISSUE THREAD

**Issue by yvone1991** [mapbox/mapbox-maps-flutter#225]
How can I remove the view highlighted with a red border on my way?
<img width="538" alt="image" src="https://github.com/mapbox/mapbox-maps-flutter/assets/10139374/b2d59472-f3b9-4e16-b321-1d83fd3fb3a6">

**Comment by TSxSAHIL** [comment]
Can I get to know what is the issue abnd what are you trying to resolve? 
Please Brief

**Comment by yvone1991** [comment]
> Can I get to know what is the issue and what are you trying to resolve?
> Please Brief

The ruler in the top left corner and the logo in the bottom left corner should be removed according to our product manager, as they affect the aesthetics. However, I cannot find a method to hide them.

**Comment by TSxSAHIL** [comment]
Can you please tell the path in which this file is ?

**Comment by yvone1991** [comment]
I don't understand your point. I just want to hide the logo and the scale bar, but I'm not sure how to achieve it. With the library mapbox_gl: ^0.16.0, I can hide the logo by adjusting the margin values. However, with the library mapbox_maps_flutter: ^0.4.4, I cannot find a method to hide them.


mapbox_gl: ^0.16.0:
```
 MapboxMap(
          onMapCreated: _onMapCreated,
          accessToken: key,
          myLocationEnabled:
              pageState.pageStatus == PageInteractionStatus.locateVehicle
                  ? true
                  : false,
          myLocationTrackingMode: MyLocationTrackingMode.None, 

          initialCameraPosition:
              const CameraPosition(target: LatLng(0, 0), zoom: 1),
          annotationOrder: const [
            AnnotationType.fill,
            AnnotationType.line,
            AnnotationType.circle,
            AnnotationType.symbol
          ],
          onUserLocationUpdated: (location) async {
            _locationCubit.refreshLocation(location.position);
          },
          compassEnabled: false,
          rotateGesturesEnabled: false,
          trackCameraPosition: false, 
          onStyleLoadedCallback: _onStyleCallBack,
          styleString: lightStyle,
          **logoViewMargins: const Point(-100, -100), 
          attributionButtonMargins: const Point(-100, -100),** 
        )
```


mapbox_maps_flutter: ^0.4.4

```
MapWidget(
      resourceOptions: ResourceOptions(accessToken: key),
      onMapCreated: _onMapCreated,
      onStyleLoadedListener: _onStyleCallBack,
      styleUri: lightStyle,
    )
```

**Comment by yvone1991** [comment]
> Can you please tell the path in which this file is ?

I don't understand your point. I just want to hide the logo and the scale bar, but I'm not sure how to achieve it. 

With the library mapbox_gl: ^0.16.0, I can hide the logo by adjusting the margin values. 

```
logoViewMargins: const Point(-100, -100), 
attributionButtonMargins: const Point(-100, -100)
```


However, with the library mapbox_maps_flutter: ^0.4.4, I cannot find a method to hide them.


mapbox_gl: ^0.16.0:
```
 MapboxMap(
          onMapCreated: _onMapCreated,
          accessToken: key,
          myLocationEnabled:
              pageState.pageStatus == PageInteractionStatus.locateVehicle
                  ? true
                  : false,
          myLocationTrackingMode: MyLocationTrackingMode.None, 

          initialCameraPosition:
              const CameraPosition(target: LatLng(0, 0), zoom: 1),
          annotationOrder: const [
            AnnotationType.fill,
            AnnotationType.line,
            AnnotationType.circle,
            AnnotationType.symbol
          ],
          onUserLocationUpdated: (location) async {
            _locationCubit.refreshLocation(location.position);
          },
          compassEnabled: false,
          rotateGesturesEnabled: false,
          trackCameraPosition: false, 
          onStyleLoadedCallback: _onStyleCallBack,
          styleString: lightStyle,
          logoViewMargins: const Point(-100, -100), 
          attributionButtonMargins: const Point(-100, -100),
        )
```


mapbox_maps_flutter: ^0.4.4

```
MapWidget(
      resourceOptions: ResourceOptions(accessToken: key),
      onMapCreated: _onMapCreated,
      onStyleLoadedListener: _onStyleCallBack,
      styleUri: lightStyle,
    )
```

**Comment by kamami** [comment]
I am not sure if you should remove the logo. It is a contribution to the company, as they are providing the service you are using.

**Comment by yvone1991** [comment]
> I am not sure if you should remove the logo. It is a contribution to the company, as they are providing the service you are using.

Can the ruler be removed? The logo doesn't matter.

**Comment by markpeterfejes** [comment]
In your onMapCreated function, alter the map settings like so: 

```dart
_onMapCreated(MapboxMap mapboxMap) {
    this.mapboxMap = mapboxMap
      ..scaleBar.updateSettings(ScaleBarSettings(enabled: false))
      ..compass.updateSettings(CompassSettings(enabled: false));
  }
```

Hope this helps,
