### ISSUE TITLE
Issue Regarding the Display of China's National Border Lines

### ISSUE THREAD

**Issue by OneupLee** [mapbox/mapbox-maps-flutter#226]
Hello, Mapbox,

I have encountered an issue with national border lines while using Mapbox. We are developers from China, and we truly appreciate the level of detail Mapbox offers. As a result, we have integrated Mapbox maps into certain services within our app. However, we are facing an issue when configuring the "Worldview" within "Administrative boundaries" to "CN."

The problem arises specifically with the border markings of China's Heilongjiang Province in the area of "Fuyuan" on "黑瞎子岛" (English translation: Bolshoy Ussuriysky Island). The current representation of China's national border in this area does not align with the actual situation. The actual border should be as shown in the red-marked area in the image below:
![image](https://github.com/mapbox/mapbox-maps-flutter/assets/32166473/fc4b59b6-427e-415d-a06b-5bbd7ea68ec3)
![image](https://github.com/mapbox/mapbox-maps-flutter/assets/32166473/926d0fd4-2488-46ec-bfc6-9ca685c81249)
![image](https://github.com/mapbox/mapbox-maps-flutter/assets/32166473/59100fb1-9a58-446a-b48a-574125d7a3d5)
![image](https://github.com/mapbox/mapbox-maps-flutter/assets/32166473/1840952c-c3f1-4e18-9ecf-10794e7f1022)
If this issue is not resolved, we, as an app providing services to Chinese users, will be unable to display the national border lines accurately. We would only be able to continue hiding them. On September 2nd, China also released a confirmation of the new map, clearly marking and explaining the border lines in this area.

Therefore, I kindly request that you investigate whether this issue can be resolved. We look forward to your response. Thank you.

**Comment by sbma44** [comment]
Thank you @OneupLee. We are evaluating the most appropriate way to respond to this recent policy change by the Chinese government. We appreciate your patience as we do so. In the meantime, we recommend continuing to suppress these borders if you are concerned about compliance.

**Comment by OneupLee** [comment]
Thanks Reply @sbma44 . It seems that for now we can only find a way to solve this problem ourselves.

**Comment by MePride** [comment]
How did you solve it?

**Comment by OneupLee** [comment]
@MePride I think you can download the border data from the official website and draw it.

**Comment by venus-yangbo** [comment]
> @MePride我想你可以从官网下载边框数据并绘制出来。

我也遇到了合规问题。想请问下，在flutter这边，应该如何设置worldview？
