### ISSUE TITLE
Feature request: layer style expressions

### ISSUE THREAD

**Issue by irjayjay** [mapbox/mapbox-maps-flutter#23]
Hi, and firstly, well done with the plugin. It is phenomenal!
Our team has been using the other unofficial plugin for a few years now. It was the best there was, but we had extreme performance issues and some difficulty adding custom layers, etc.
We finally hacked in layer/layer-style support, but it's not great.

Your plugin is extremely fast, I've been testing it for viability for the last two days.
So far only this one possible deal breaker.

In our app we use, e.g. symbol layers where the symbols have filters that make them disappear at zoom level 5 and below and also reduces their size linearly based on zoom level. We can also set symbol images on a single layer based on expressions such as the GET expression from [the Mapbox docs](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#get).

Are there any plans to allow for adding these expressions? 
I see currently when creating a layer you can only set a size of type double, as an example.

I'm gonna explore your code a bit and see if I can somehow pass in custom JSON directly somewhere, but the layer data classes do make things a lot easier.

**Comment by kamami** [comment]
This can already be achieved with interpolate:


```
{
    "circle-radius": [
        "interpolate", ["linear"], ["zoom"],
        // zoom is 5 (or less) -> circle radius will be 1px
        5, 1,
        // zoom is 10 (or greater) -> circle radius will be 5px
        10, 5
    ]
}
```

**Comment by irjayjay** [comment]
Hi, thanks for your reply.

Yeah, we used to use interpolate for that. 
I just couldn't find mention of any layer styles in the readme or demo app.
Now searching for interpolate in the project I see it gets used with layer styles once. A bit of hay in a needle stack.

Thanks for this! Perhaps it can be mentioned in the readme? 
I think most devs new to Mapbox wouldn't be aware of layer styles or even think to search for them in the demo app.

**Comment by yunikkk** [comment]
@irjayjay hey, there's not a lot of docs about expressions usage at the moment (though seems you've found the [animated route](https://github.com/mapbox/mapbox-maps-flutter/blob/main/example/lib/animated_route.dart#L236) page that uses `interpolate`). 
We'll definitely work on adding more!

**Comment by geisterfurz007** [comment]
@demux79 Make sure the layer is added to the styles before you try to set the style layer property; for that, make sure to `await` the call to `addLayer`.

**Comment by geisterfurz007** [comment]
@demux79 There is one `await` missing at the second larger block in front of `mapboxMap?.style.styleLayerExists`.
