### ISSUE TITLE
Display Direction API

### ISSUE THREAD

**Issue by marcotrumpet** [mapbox/mapbox-maps-flutter#236]
Is it possible to call mapbox direction api and display (just display) the polyline in the map? I'm not interested in navigating it, only in displaying routes

**Comment by ENRexGeorge23** [comment]
yes it it possible

**Comment by ENRexGeorge23** [comment]
You can use this code 



```
  @override
  void onPointAnnotationClick(PointAnnotation annotation) async {
    if (await mapState.mapboxMap.style.styleSourceExists("source")) {
      await mapState.mapboxMap.style.removeStyleLayer("layer");
      await mapState.mapboxMap.style.removeStyleSource("source");
    }

    // build route from puck position to the clicked annotation
    final start = await mapState.mapboxMap.style.getPuckPosition();
    final end = Point.fromJson((annotation.geometry)!.cast());

    final coordinates = await fetchRouteCoordinates(
        start, end.coordinates, MapsDemo.ACCESS_TOKEN);

    drawRouteLowLevel(coordinates);
  }
```

then this is how you can dispaly the polylines

 ```
 void drawRouteLowLevel(List<Position> polyline) async {
    final line = LineString(coordinates: polyline);

    mapState.mapboxMap.style.styleSourceExists("source").then((exists) async {
      if (exists) {
        // If source exists, just update it
        final source = await mapState.mapboxMap.style.getSource("source");
        (source as GeoJsonSource).updateGeoJSON(json.encode(line));
      } else {
        await mapState.mapboxMap.style.addSource(GeoJsonSource(
          id: "source",
          data: json.encode(line),
          lineMetrics: true,
        ));

        await mapState.mapboxMap.style.addLayer(LineLayer(
          id: 'layer',
          sourceId: 'source',
          lineCap: LineCap.ROUND,
          lineJoin: LineJoin.ROUND,
          lineBlur: 1.0,
          lineColor: Color.fromARGB(255, 128, 0, 128).value, // Blue color
          lineWidth: 5.0,
        ));
      }

      // Query line layer
      final lineLayer =
          await mapState.mapboxMap.style.getLayer('layer') as LineLayer;

      // animate layer to reveal it from start to end
      controller?.stop();
      controller = AnimationController(
          duration: const Duration(seconds: 2), vsync: mapState);
      animation = Tween<double>(begin: 0, end: 1.0).animate(controller!)
        ..addListener(() async {
          lineLayer.lineTrimOffset = [animation?.value, 1.0];
          mapState.mapboxMap.style.updateLayer(lineLayer);
        });
      controller?.forward();
    });
  }
}
```

this is based from the example that was provided by the mapbox team

**Comment by marcotrumpet** [comment]
> You can use this code
> 
> ```
>   @override
>   void onPointAnnotationClick(PointAnnotation annotation) async {
>     if (await mapState.mapboxMap.style.styleSourceExists("source")) {
>       await mapState.mapboxMap.style.removeStyleLayer("layer");
>       await mapState.mapboxMap.style.removeStyleSource("source");
>     }
> 
>     // build route from puck position to the clicked annotation
>     final start = await mapState.mapboxMap.style.getPuckPosition();
>     final end = Point.fromJson((annotation.geometry)!.cast());
> 
>     final coordinates = await fetchRouteCoordinates(
>         start, end.coordinates, MapsDemo.ACCESS_TOKEN);
> 
>     drawRouteLowLevel(coordinates);
>   }
> ```
> 
> then this is how you can dispaly the polylines
> 
> ```
> void drawRouteLowLevel(List<Position> polyline) async {
>    final line = LineString(coordinates: polyline);
> 
>    mapState.mapboxMap.style.styleSourceExists("source").then((exists) async {
>      if (exists) {
>        // If source exists, just update it
>        final source = await mapState.mapboxMap.style.getSource("source");
>        (source as GeoJsonSource).updateGeoJSON(json.encode(line));
>      } else {
>        await mapState.mapboxMap.style.addSource(GeoJsonSource(
>          id: "source",
>          data: json.encode(line),
>          lineMetrics: true,
>        ));
> 
>        await mapState.mapboxMap.style.addLayer(LineLayer(
>          id: 'layer',
>          sourceId: 'source',
>          lineCap: LineCap.ROUND,
>          lineJoin: LineJoin.ROUND,
>          lineBlur: 1.0,
>          lineColor: Color.fromARGB(255, 128, 0, 128).value, // Blue color
>          lineWidth: 5.0,
>        ));
>      }
> 
>      // Query line layer
>      final lineLayer =
>          await mapState.mapboxMap.style.getLayer('layer') as LineLayer;
> 
>      // animate layer to reveal it from start to end
>      controller?.stop();
>      controller = AnimationController(
>          duration: const Duration(seconds: 2), vsync: mapState);
>      animation = Tween<double>(begin: 0, end: 1.0).animate(controller!)
>        ..addListener(() async {
>          lineLayer.lineTrimOffset = [animation?.value, 1.0];
>          mapState.mapboxMap.style.updateLayer(lineLayer);
>        });
>      controller?.forward();
>    });
>  }
> }
> ```
> 
> this is based from the example that was provided by the mapbox team

Thanks man, I was indeed able to call directions api and display the geometry, thanks again
