### ISSUE TITLE
iOS - image disappears when updating point annotation

### ISSUE THREAD

**Issue by FirentisTFW** [mapbox/mapbox-maps-flutter#241]
On iOS when we use `pointAnnotationManager?.update`, the point annotation gets updated, but the image disappears. It works fine on Android. 

**Steps:**
1. Open example app
2. Tap on `Point Annotations` tile
3. Tap on `delete on point annotations` button to clear the view
4. Tap on `create a point annotation` button to create a fresh annotation
5. Tap on `update a point annotation` button
6. Verify the result

**Expected result:**
Image gets moved together with point annotation.

**Actual result:**
Image disappears when the point annotation is moved.

**Video:**

https://github.com/mapbox/mapbox-maps-flutter/assets/55327556/25a26e6b-bca3-4d1c-98ae-0a56bd5a4bc5

**Comment by OneupLee** [comment]
maybe you can fix it like [this](https://github.com/OneupLee/mapbox-maps-flutter/pull/1#issue-1912766858)

**Comment by evil159** [comment]
Hi @FirentisTFW, thank you for the report! This issue should be fixed in #350
