### ISSUE TITLE
ScaleBox, Attributions, Compass Setting Interfaces not available for use

### ISSUE THREAD

**Issue by praveentcom** [mapbox/mapbox-maps-flutter#25]
Only the `LogoSettingsInterface` is exposed via `MapboxMap.logo`.

There is no way to hide the ScaleBox via code. However, we can see that the necessary classes and interfaces to modify the ScaleBox and other counterparts are available but not exposed to use.

Please expose `MapboxMap.scaleBox` and `MapboxMap.attributions` with the next version.

**Comment by dawid-niedzwiecki** [comment]
I would also need those features :D

**Comment by geisterfurz007** [comment]
Version 0.4.0 was recently released which exposes those things!

**Comment by yunikkk** [comment]
Became available with 0.4.0.
