### ISSUE TITLE
Map is rerendering every frame when keyboard appears/disappears

### ISSUE THREAD

**Issue by kamami** [mapbox/mapbox-maps-flutter#26]
The `_onMapCreated` function is triggered every single frame, when the soft keyboard is appearing or disappearing.

```
_onMapCreated(MapboxMap mapboxMap) async {
    print("ONMAPCREATED");
//Prints to console every single frame
}
```

Console:

flutter: ONMAPCREATED
flutter: ONMAPCREATED
flutter: ONMAPCREATED
flutter: ONMAPCREATED
flutter: ONMAPCREATED
flutter: ONMAPCREATED
flutter: ONMAPCREATED
flutter: ONMAPCREATED
flutter: ONMAPCREATED
flutter: ONMAPCREATED
flutter: ONMAPCREATED
flutter: ONMAPCREATED
flutter: ONMAPCREATED
flutter: ONMAPCREATED
flutter: ONMAPCREATED
flutter: ONMAPCREATED

**Comment by dawid-niedzwiecki** [comment]
Sorry, made a typo in my issue :/
