### ISSUE TITLE
Compass Image size in iOS is huge, but not in Android

### ISSUE THREAD

**Issue by securexperts** [mapbox/mapbox-maps-flutter#269]
When I use the Fonction
 `mapboxMap.compass.updateSettings(
        CompassSettings(
          visibility: true,
          clickable: true,
          image: uint8List,
          opacity: 0.8,
          marginTop: compasPosition,
          marginRight: 20,
        )
    );`

the Image Size cannot be defined and there is no option to give size nor automatic to do it.
The only way to get a correct size is to reduce the raw image size and use this.
On Android devices this function works correctly.

**Comment by evil159** [comment]
@securexperts on iOS compass view inherits its size from its image, make sure to provide the image in the desired size to ensure proper appearance for compass.
