### ISSUE TITLE
Failed to build iOS app

### ISSUE THREAD

**Issue by MarMarLwin-Ninja** [mapbox/mapbox-maps-flutter#271]
iOS Build fail after I download new version of Mapbox-maps-flutter
<img width="1027" alt="Screenshot 2023-10-14 at 08 43 55" src="https://github.com/mapbox/mapbox-maps-flutter/assets/143772024/65febe86-098f-4991-a7ff-f0f71e545326">

**Comment by ruchitmavani** [comment]
@MarMarLwin-Ninja You can use mapbox_maps_flutter: 0.4.4 for now!

The issue should be resolved soon until then use 0.4.4!

**Comment by evil159** [comment]
Should be resolved with Xcode 15.
