### ISSUE TITLE
How to offset Mapbox Information

### ISSUE THREAD

**Issue by securexperts** [mapbox/mapbox-maps-flutter#272]
Hello to all

I like to offset / padding the "Powered by Mapbox Maps" Information on the bottom Left Corner Padding  a little bit up (just above my Bottom menu which disappears when it is not used) The Map must be on Full Screen.

<img width="616" alt="image" src="https://github.com/mapbox/mapbox-maps-flutter/assets/38250878/aed65eb8-1a86-4390-b5c4-7f81bb36bf97">

Eben more better would be if it can be dynamically placed, depend on showing my bottom menu.

Thanks

**Comment by Xennis** [comment]
Hi @securexperts ,

Look into the `LogoSettings` class. Here some example usage from my application (with `MapboxMap _mapboxMap`):

```dart
        _mapboxMap.logo.updateSettings(LogoSettings(marginBottom: 25.0));
        _mapboxMap.attribution.updateSettings(AttributionSettings(marginBottom: 25.0));
```
