### ISSUE TITLE
Customize cluster with an image + text

### ISSUE THREAD

**Issue by flaviopopoff** [mapbox/mapbox-maps-flutter#281]
Hi! Its possible to customize the cluster marker?
I have a cluster like this: [classic cluster](https://developers.google.com/static/maps/documentation/ios-sdk/images/clustering-default-icon.png)
I want this: [Instagram cluster](https://akm-img-a-in.tosshub.com/businesstoday/images/story/202207/fydpbchuyaeuvgu_1-sixteen_nine.jpg?size=948:533)

With the combo "Name +3 more", Is it possible? How can I do it?

**Comment by vanvixi** [comment]
@flaviopopoff 
Is it true what you want?
https://github.com/mapbox/mapbox-maps-flutter/issues/278#issuecomment-1786380170

**Comment by flaviopopoff** [comment]
@vanvixi yeah something like this, but with cluster, if I have multiple annotations/marker the map it's a confusion when I zoom out

**Comment by vanvixi** [comment]
@flaviopopoff 
Do you mean that the annotations/market stack on top of each other?
If you face this issue, please config following things: 
```
    final pointManager = await mapboxMap.annotations.createPointAnnotationManager();

    await pointManager!.setIconAllowOverlap(false);
    await pointManager!.setIconIgnorePlacement(false);
    await pointManager!.setTextOptional(false);
    await pointManager!.setTextAllowOverlap(false);
    await pointManager!.setTextIgnorePlacement(false);
```

Also, you should also set `symbolSortKey` for annotations/market

**Comment by flaviopopoff** [comment]
@vanvixi ok, with the pointManager now working fine, thank you so much!
