### ISSUE TITLE
Adding MapWidget causes Unhandled Exception

### ISSUE THREAD

**Issue by kinga112** [mapbox/mapbox-maps-flutter#291]
I just added the widget as a child to a container to try to get it working.

MapWidget(
            resourceOptions: ResourceOptions(
                accessToken: dotenv.env['MAPBOX_ACCESS_TOKEN']!))

I added my access token to the locations posted in the read me.

E/flutter (32061): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Please ensure that the hosting activity/fragment 
is a valid LifecycleOwner
E/flutter (32061):      at com.mapbox.maps.plugin.lifecycle.ViewLifecycleOwner.doOnAttached(ViewLifecycleOwner.kt:68)

**Comment by Ashok-Media** [comment]
got any solution? @kinga112

**Comment by evil159** [comment]
Hi all, this issue should be fixed in https://github.com/mapbox/mapbox-maps-flutter/pull/478, feel free to reopen this ticket if you have any feedback!
