### ISSUE TITLE
E/flutter (12658): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Please ensure that the hosting activity/fragment is a valid LifecycleOwner

### ISSUE THREAD

**Issue by OnlineNomad** [mapbox/mapbox-maps-flutter#308]
help

**Comment by OnlineNomad** [comment]
pubsec.yaml:
name: aqari_official
description: "flutter official mapbox integration"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  mapbox_maps_flutter: ^0.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages




main.dart:
import 'package:flutter/material.dart';
import 'package:mapbox_maps_flutter/mapbox_maps_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MapWidget(
        styleUri: 'mapbox://styles/aqariapp/cl8pyjlgh001314t5w94h3s82',
        resourceOptions: ResourceOptions(
            accessToken:
                'my token is here'),
      ),
    );
  }
}


android/build.gradle 

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://api.mapbox.com/downloads/v2/releases/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                // Do not change the username below.
                // This should always be `mapbox` (not your username).
                username = "mapbox"
                // Use the secret token you stored in gradle.properties as the password
                password = project.properties['MAPBOX_DOWNLOADS_TOKEN'] ?: "my secret token is here"
            }
        }
    }
}
android/app/build.gradle

dependencies {
    implementation 'com.mapbox.maps:android:10.16.2'
}



i have the secret token in gradle.properties too.





run log: 


A Dart VM Service on Google ATD built for x86 64 is available at: http://127.0.0.1:54880/JrrTa-g5Y3g=/
I/.aqari_official( 3168): Compiler allocated 4533KB to compile void android.view.ViewRootImpl.performTraversals()
W/.aqari_official( 3168): Accessing hidden field Landroid/graphics/Typeface;->sSystemFontMap:Ljava/util/Map; (unsupported, reflection, allowed)
I/Mbgl-FontUtils( 3168): Couldn't map font family for local ideograph, using sans-serif instead
I/Mapbox  ( 3168): [threading]: Worker 1 priority is now 4
I/Mapbox  ( 3168): [threading]: Worker 2 priority is now 4
I/Mapbox  ( 3168): [threading]: Worker 3 priority is now 4
I/Mapbox  ( 3168): [threading]: Worker 1 priority is now 4
I/Mapbox  ( 3168): [threading]: Worker 1 priority is now 4
I/Mapbox  ( 3168): [threading]: Worker 1 priority is now 4
I/Mapbox  ( 3168): [threading]: Worker 1 priority is now 4
I/Mapbox  ( 3168): [threading]: Worker 4 priority is now 4
I/Mapbox  ( 3168): [threading]: Worker 1 priority is now 4
I/Mapbox  ( 3168): [threading]: ResourceLoaderT priority is now 4
I/Mapbox  ( 3168): [threading]: LocalFileSource priority is now 4
I/Mapbox  ( 3168): [threading]: TileStoreFileSo priority is now 4
I/Mapbox  ( 3168): [threading]: AssetManagerFil priority is now 4
W/Mapbox  ( 3168): [metrics]: Can't obtain default mapbox access token from SystemInformationProvider. MetricsService won't send any events.
I/Mapbox  ( 3168): [threading]: OnlineFileSourc priority is now 4
I/Mapbox  ( 3168): [MapboxReachability]: Application permission for ACCESS_NETWORK_STATE granted
E/ThemeUtils( 3168): View class com.mapbox.maps.plugin.compass.CompassViewImpl is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
W/Mapbox  ( 3168): [config_service]: No configuration options found stored on the disk.
E/ThemeUtils( 3168): View class com.mapbox.maps.plugin.logo.LogoViewImpl is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
I/Mapbox  ( 3168): [threading]: Worker 1 priority is now 4
E/Mapbox  ( 3168): [maps-core]: {Worker 2}[General]: Unable to get stored configuration: No configuration options found stored on the disk.
E/ThemeUtils( 3168): View class com.mapbox.maps.plugin.attribution.AttributionViewImpl is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
W/Mapbox  ( 3168): [config_service]: No configuration options found stored on the disk.
W/Mapbox  ( 3168): [config_service]: Update request 1 in progress (attempt 0 of 2)
W/Mapbox  ( 3168): [config_service]: Update request 1 in progress (attempt 0 of 2)
W/Mapbox  ( 3168): [config_service]: Update request 1 in progress (attempt 0 of 2)
I/Mapbox  ( 3168): [maps-android\Mbgl-RenderThread]: Renderer resumed, renderThreadPrepared=false, surface.isValid=null
I/Mapbox  ( 3168): [maps-android\Mbgl-RenderThread]: renderThreadPrepared=false and Android surface is not valid (isValid=null). Waiting for new one.
I/PlatformViewsController( 3168): Hosting view in view hierarchy for platform view: 0
I/Mapbox  ( 3168): [maps-android\Mbgl-RenderThread]: renderThreadPrepared=false and Android surface is not valid (isValid=null). Waiting for new one.
I/Mapbox  ( 3168): [maps-android\Mbgl-RenderThread]: renderThreadPrepared=false and Android surface is not valid (isValid=null). Waiting for new one.
W/Parcel  ( 3168): Expecting binder but got null!
The Flutter DevTools debugger and profiler on Google ATD built for x86 64 is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:54880/JrrTa-g5Y3g=/
D/TrafficStats( 3168): tagSocket(132) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 3168): tagSocket(131) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 3168): tagSocket(133) with statsTag=0xffffffff, statsUid=-1
E/flutter ( 3168): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Please ensure that the hosting activity/fragment is a valid LifecycleOwner
E/flutter ( 3168):      at com.mapbox.maps.plugin.lifecycle.ViewLifecycleOwner.doOnAttached(ViewLifecycleOwner.kt:68)
E/flutter ( 3168):      at com.mapbox.maps.plugin.lifecycle.ViewLifecycleOwner.<init>(ViewLifecycleOwner.kt:58)
E/flutter ( 3168):      at com.mapbox.maps.plugin.lifecycle.MapboxLifecyclePluginImpl.registerLifecycleObserver(MapboxLifecyclePluginImpl.kt:30)
E/flutter ( 3168):      at com.mapbox.maps.plugin.MapPluginRegistry.onAttachedToWindow(MapPluginRegistry.kt:173)
E/flutter ( 3168):      at com.mapbox.maps.MapController.onAttachedToWindow$sdk_publicRelease(MapController.kt:346)
E/flutter ( 3168):      at com.mapbox.maps.MapView.onAttachedToWindow(MapView.kt:129)
E/flutter ( 3168):      at android.view.View.dispatchAttachedToWindow(View.java:21290)
E/flutter ( 3168):      at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3491)
E/flutter ( 3168):      at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
E/flutter ( 3168):      at android.view.ViewGroup.addViewInner(ViewGroup.java:5291)
E/flutter ( 3168):      at android.view.ViewGroup.addView(ViewGroup.java:5077)
E/flutter ( 3168):      at android.view.ViewGroup.addView(ViewGroup.java:5017)
E/flutter ( 3168):      at android.view.ViewGroup.addView(ViewGroup.java:4989)
E/flutter ( 3168):      at io.flutter.plugin.platform.PlatformViewsController.configureForTextureLayerComposition(PlatformViewsController.java:658)
E/flutter ( 3168):      at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:227)    
E/flutter ( 3168):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:128)
E/flutter ( 3168):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)    
E/flutter ( 3168):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/flutter ( 3168):      at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter ( 3168):      at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter ( 3168):      at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 3168):      at android.os.Handler.handleCallback(Handler.java:942)
E/flutter ( 3168):      at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 3168):      at android.os.Looper.loopOnce(Looper.java:201)
E/flutter ( 3168):      at android.os.Looper.loop(Looper.java:288)
E/flutter ( 3168):      at android.app.ActivityThread.main(ActivityThread.java:7872)
E/flutter ( 3168):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 3168):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter ( 3168):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/flutter ( 3168): , null, null)
E/flutter ( 3168): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
E/flutter ( 3168): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:322:18)
E/flutter ( 3168): <asynchronous suspension>
E/flutter ( 3168): #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1141:28)      
E/flutter ( 3168): <asynchronous suspension>
E/flutter ( 3168): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:804:5)
E/flutter ( 3168): <asynchronous suspension>
E/flutter ( 3168): #4      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:831:7)
E/flutter ( 3168): <asynchronous suspension>
E/flutter ( 3168): #5      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:175:29)
E/flutter ( 3168): <asynchronous suspension>
E/flutter ( 3168):
D/TrafficStats( 3168): tagSocket(134) with statsTag=0xffffffff, statsUid=-1
I/Mapbox  ( 3168): [LifecycleUtils]: Task: TaskInfo{userId=0 taskId=5 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x30000000 cmp=com.aqari.aqari_official/.MainActivity (has extras) } baseActivity=ComponentInfo{com.aqari.aqari_official/com.aqari.aqari_official.MainActivity} topActivity=ComponentInfo{com.aqari.aqari_official/com.aqari.aqari_official.MainActivity} origActivity=null realActivity=ComponentInfo{com.aqari.aqari_official/com.aqari.aqari_official.MainActivity} numActivities=1 lastActiveTime=119318 supportsMultiWindow=true resizeMode=1 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{android.window.IWindowContainerToken$Stub$Proxy@ae6dea8} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 displayCutoutSafeInsets=Rect(0, 128 - 0, 0) topActivityInfo=ActivityInfo{a142dc1 com.aqari.aqari_official.MainActivity} launchCookies=[] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=true isVisible=false isSleeping=false topActivityInSizeCompat=false topActivityEligibleForLetterboxEducation= false locusId=null displayAreaFeatureId=1 cameraCompatControlState=hidden}

**Comment by kinga112** [comment]
Look at this PR: 
0459357

**Comment by kinga112** [comment]
That fixed it for me

**Comment by Alexgi2002** [comment]
I have same problem... Flutter 3.19.0 Dart 3.0

**Comment by OnlineNomad** [comment]
Chose react-native instead
