### ISSUE TITLE
How to update the source when it's already in the map?

### ISSUE THREAD

**Issue by dawid-niedzwiecki** [mapbox/mapbox-maps-flutter#31]
How can I update the source when it's already in the map? Do I have to remove it first? I wrote such a method:

```dart
  Future<void> _removeSourceIfExists(String sourceId) async {
    if (!mounted) return;
    if (await mapController.style.styleSourceExists(sourceId)) {
      await mapController.style.removeStyleSource(sourceId);
    }
  }

  Future<void> _addSource(String sourceId, Map<String, dynamic> geojson) async {
    await mapController.style
        .addSource(GeoJsonSource(id: sourceId, data: json.encode(geojson)));
  }
```

But when removing a source, I get the error :
```
PlatformException (PlatformException(Throwable, java.lang.Throwable: Source 'markerSource' is in
use, cannot remove, Cause: null, Stacktrace: java.lang.Throwable: Source 'markerSource' is in use, 
cannot remove
```

I also tried just adding the updated source, without removing it beforehand, but then I get the following error:
```
PlatformException (PlatformException(Throwable, java.lang.Throwable: Source markerSource already exists, 
Cause: null, Stacktrace: java.lang.Throwable: Source markerSource already exists
at com.mapbox.maps.mapbox_maps.StyleController.addStyleSource$lambda-21(StyleController.kt:256)
```

**Comment by LjubiTech-Maxko** [comment]
To update already existing source use the following:

```
final GeoJsonSource source = await mapController.style.getSource(sourceId) as GeoJsonSource;
await source.updateGeoJSON(jsonEncode(geojson));
```
<br/>  

> But when removing a source, I get the error :
> 
> ```
> PlatformException (PlatformException(Throwable, java.lang.Throwable: Source 'markerSource' is in
> use, cannot remove, Cause: null, Stacktrace: java.lang.Throwable: Source 'markerSource' is in use, 
> cannot remove
> ```
When removing the source you should first remove all the layers that are using that source, and then you can remove the source.  

<br/>  

> I also tried just adding the updated source, without removing it beforehand, but then I get the following error:
> 
> ```
> PlatformException (PlatformException(Throwable, java.lang.Throwable: Source markerSource already exists, 
> Cause: null, Stacktrace: java.lang.Throwable: Source markerSource already exists
> at com.mapbox.maps.mapbox_maps.StyleController.addStyleSource$lambda-21(StyleController.kt:256)
> ```

You can't have 2 sources with the same id, which hapens because you didn't remove the source before adding new.

**Comment by dawid-niedzwiecki** [comment]
Thanks, do you also know a quick way to hide and show a layer? :D

**Comment by dawid-niedzwiecki** [comment]
Thank you very much!

**Comment by roly151** [comment]
Does this also work with Vector Sources?

**Comment by roly151** [comment]
@LjubiTech-Maxko Are you able to assist with my question I added after the issue was closed?
