### ISSUE TITLE
How can i show my current location node

### ISSUE THREAD

**Issue by vickygaugau** [mapbox/mapbox-maps-flutter#316]
Hi everyone
I am using this library
I want to show the current location (display the blue circle in the current location)
But i don't know how to do that
Can you help me
Thanks

**Comment by Xennis** [comment]
Hey @vickygaugau , did you see the example app? You find in this app also an example of displaying the current location on the map: https://github.com/mapbox/mapbox-maps-flutter/blob/main/example/lib/location.dart

**Comment by vickygaugau** [comment]
Hi
I found the example code
Thanks alot
