### ISSUE TITLE
All of issues there in mapbox-maps-flutter

### ISSUE THREAD

**Issue by QBlockQ** [mapbox/mapbox-maps-flutter#319]
We stopped working after found all of issues there in mapbox-maps-flutter.  We strongly recommend to refractory this repo.  For further information, please let's know.

**Comment by Xaliljon** [comment]
why?

**Comment by baleboy** [comment]
Thank you for taking the time to share your feedback. Please know that we are committed to improving this project. If any of the issues reported here are particularly impactful for you, please feel free to point them out.

**Comment by QBlockQ** [comment]
Sorry to say this but we have to say it.  This is not a standard clean code, alot of complicated architecture with unneeded bugs.  There are huge set ups there where more optimizations can be achieved with less and simple code.  For further information, please let's know
