### ISSUE TITLE
Pass Custom Data through PointAnnotation

### ISSUE THREAD

**Issue by ggever** [mapbox/mapbox-maps-flutter#32]
Hello. First of all, I really love this project. Thank you so much for your working on it. I am now stucking with passing custom data through PointAnnotaion.

I have some markers/anotations on the Map. When clicking on a marker, base on the marker's id, it will get data of that marker and display it. But it seems that there is no field for that purpose in PointAnnotation.

Here is my source. How can I do this?
> 
  @override
  void onPointAnnotationClick(PointAnnotation annotation) async {
        Navigator.pushNamed(mapState.context, Routes.viewPinInfo, arguments: **annotation.customData.id**);
  }

**Comment by LjubiTech-Maxko** [comment]
This is currently not possible. As a workaround you could add your data as geojson source with custom properties you need, display it through layer and later query the map for the feature when the map is clicked to get the custom data.

**Comment by ggever** [comment]
Thank you sir, it worked.
