### ISSUE TITLE
 Request for Update to Mapbox SDK 11.0.0 in mapbox-maps-flutter Plugin

### ISSUE THREAD

**Issue by shihanjun19** [mapbox/mapbox-maps-flutter#329]
I've noticed that the Mapbox SDK has recently been updated to version 11.0.0, but the mapbox-maps-flutter plugin is still using the older 10.13.0 SDK version. 

Could you please share any plans to update the plugin to align with the latest Mapbox SDK version? An upgrade would enable us to leverage the new features and improvements available in SDK 11.0.0.

If an update is in the pipeline, could you provide an estimated timeline for its release?

Thanks for your work on maintaining this plugin, and looking forward to the possibility of using the updated SDK features in Flutter.

**Comment by baleboy** [comment]
Hi @shihanjun19, thank you for your interest in the mapbox-maps-flutter plugin and your kind words. I can confirm that our team is actively working on an update to the Mapbox SDK 11.0.0. However, we are currently unable to provide a specific timeline for the release.

May I ask what features in v11.0.0 you are especially interested about?

**Comment by Menusyes** [comment]
> Hi @shihanjun19, thank you for your interest in the mapbox-maps-flutter plugin and your kind words. I can confirm that our team is actively working on an update to the Mapbox SDK 11.0.0. However, we are currently unable to provide a specific timeline for the release.
> 
> May I ask what features in v11.0.0 you are especially interested about?

For me, I want to try `Standard ` style. I tried on the V10, but the building was blank.

**Comment by evil159** [comment]
Hi @Menusyes, thank you for highlighting this, we've released Mapbox Maps Flutter Plugin v1.0.0-beta.2 that supports the Standard style.
