### ISSUE TITLE
How can I bring Marker to top and move Polyline behind marker.

### ISSUE THREAD

**Issue by sikandernoori** [mapbox/mapbox-maps-flutter#337]
<img width="98" alt="Screenshot_2023-12-26_at_6 00 06_AM" src="https://github.com/mapbox/mapbox-maps-flutter/assets/16399272/bb712a29-9e6f-48bc-bb58-9ab41c25ed38">

**Comment by steveneal** [comment]
Create separate layers for the polyline and the markers  - they will be layered in the order you declare them.

**Comment by evil159** [comment]
@steveneal Thank you for your answer! @sikandernoori Indeed, you can control layers order by adding them in desired order, alternatively you can specify layer position when adding a layer.
You can read more about layer ordering here https://docs.mapbox.com/ios/maps/guides/styles/work-with-layers/#rendering-order.
