### ISSUE TITLE
[BUG] OnTap return latitude and longitude instead of point on screen inside ScreenCoordinate object

### ISSUE THREAD

**Issue by sikandernoori** [mapbox/mapbox-maps-flutter#347]
According to Code documentation ScreenCoordinate should hold x and y points on screen:

```
/// Describes the coordinate on the screen, measured from top to bottom and from left to right.
/// Note: the `map` uses screen coordinate units measured in `logical pixels`.
class ScreenCoordinate {
  ScreenCoordinate({
    required this.x,
    required this.y,
  });

  /// A value representing the x position of this coordinate.
  double x;

  /// A value representing the y position of this coordinate.
  double y;

  Object encode() {
    return <Object?>[
      x,
      y,
    ];
  }
  ```

But OnTap gesture ScreenCoordinate object is returned  with latitude and longitude as x and y.

it should return x and y value on of screen as per documentation but in actual it is returning latitude and longitude.

Bug reproducible in example app.
Run example app -> GesturesPage -> tap on map and see coordinates in console.

https://github.com/mapbox/mapbox-maps-flutter/assets/16399272/9353b17b-2ad4-4c54-962a-666c1afaefc7

**Comment by evil159** [comment]
Hi @sikandernoori, thank you for creating this report, gesture listener API has been improved in https://github.com/mapbox/mapbox-maps-flutter/pull/473, feel free to reopen this if you have any feedback.
