### ISSUE TITLE
Update the cluster layer after filter

### ISSUE THREAD

**Issue by kamami** [mapbox/mapbox-maps-flutter#35]
How can I update my clusters, after filtering the layer of single points? The single points are responding to the filter, but the clusters are not updating to reflect the new amount of single points on the map.

**Comment by AnEpicName** [comment]
You have to update the source layer. Check @LjubiTech-Maxko's answer in the issue #31 for a more detailed explanation about that process.

It worked for me and I'm doing something similar in my app.

**Comment by kamami** [comment]
Thank you I managed to get it to work. Closing this.
