### ISSUE TITLE
I need to use turf version 0.0.8. When can you update it on pub.dev

### ISSUE THREAD

**Issue by xiaomaxuetu** [mapbox/mapbox-maps-flutter#361]

**Comment by evil159** [comment]
Mapbox Maps Flutter Plugin has a relaxed dependency on turf `0.0.7` and up - https://github.com/mapbox/mapbox-maps-flutter/blob/3f5f734c341d66c23694bc4f763706a0514992e9/pubspec.yaml#L15.
You should be able to update the turf version by running `pub get upgrade`.
Alternatively, Mapbox Maps Flutter Plugin v1.0.0.-beta.1 already depends on turf v0.0.8 - https://github.com/mapbox/mapbox-maps-flutter/blob/b41df7a2d04e7ce5b13a99515c543cb8034c3684/pubspec.yaml#L15
