### ISSUE TITLE
android crash

### ISSUE THREAD

**Issue by xiaomaxuetu** [mapbox/mapbox-maps-flutter#388]
<img width="1290" alt="image" src="https://github.com/mapbox/mapbox-maps-flutter/assets/13601433/5e7e30d8-f7ab-43ab-8852-bae8d535bea3">
E/AndroidRuntime( 4678): Process: com.example.bdh_agric_app_flutter, PID: 4678
E/AndroidRuntime( 4678): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 4678): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
E/AndroidRuntime( 4678): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler$1.reply(BasicMessageChannel.java:266)
E/AndroidRuntime( 4678): 	at com.mapbox.maps.pigeons.FLTMapInterfaces$_MapInterface$2.error(FLTMapInterfaces.java:5700)
E/AndroidRuntime( 4678): 	at com.mapbox.maps.mapbox_maps.MapInterfaceController$loadStyleJson$2.onMapLoadError(MapInterfaceController.kt:36)
E/AndroidRuntime( 4678): 	at com.mapbox.maps.StyleObserver.onMapLoadError(StyleObserver.kt:113)
E/AndroidRuntime( 4678): 	at com.mapbox.maps.NativeObserver.notify(NativeObserver.kt:52)
E/AndroidRuntime( 4678): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime( 4678): 	at android.os.MessageQueue.next(MessageQueue.java:341)
E/AndroidRuntime( 4678): 	at android.os.Looper.loopOnce(Looper.java:168)
E/AndroidRuntime( 4678): 	at android.os.Looper.loop(Looper.java:299)
E/AndroidRuntime( 4678): 	at android.app.ActivityThread.main(ActivityThread.java:8123)
E/AndroidRuntime( 4678): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4678): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
E/AndroidRuntime( 4678): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

When I execute the mapboxMap?.loadStyleJson method and then execute the mapboxMap?.style.setStyleJSON method, an exception occurs in the SDK when scaling the map. iOS does not have this problem.

**Comment by deandreamatias** [comment]
How solve it @xiaomaxuetu ?
