### ISSUE TITLE
Is there a way to manipulate the location puck to snap to roads?

### ISSUE THREAD

**Issue by aamirki** [mapbox/mapbox-maps-flutter#394]
Sometimes the GPS on the devices can be slightly off which makes the location puck seem like it is on the sidewalk rather than on a road. I notice this does not happen in other applications like Google Maps, so I assume they have some road snapping in place when it detects the location puck to be "close enough" to the road. Does any such feature exist for this library?

**Comment by jafar690** [comment]
@aamirki you have to implement that manually, you can use the map matching api you need to use the map matching API for that https://docs.mapbox.com/api/navigation/map-matching/?utm_medium=pricing#map-matching-api-pricing , or if you already have a route, you can snap the off point to a point on that route using the turf.dart package.

**Comment by evil159** [comment]
@aamirki Thank you for your question, indeed, @jafar690 suggested, you can snap the a location to roads with Mapbox map matching or using turf package on device.
