### ISSUE TITLE
No such module 'MapboxCommon_Private'

### ISSUE THREAD

**Issue by Cernius** [mapbox/mapbox-maps-flutter#401]
I'm receiving this error when building the app. I've tried using different package versions, but it still won't work. Is there a solution for this?

**Error output:**
```
Swift Compiler Error (Xcode): No such module 'MapboxCommon_Private'
/Users/username/flutter_projects/huntstand/huntstand-mobile-v2/ios/Pods/MapboxMaps/Sources/MapboxMaps/Annotations/AnnotationOrchestratorImpl.swift:2:28

Uncategorized (Xcode): Command SwiftEmitModule failed with a nonzero exit code

Could not build the application for the simulator.
Error launching application on iPhone SE (3rd generation).
```

**Expected behavior**

Application should compile

**Actual behavior**

Compilation always fails.

**Is this a one-time issue or a repeatable issue?**

Repeatable

Flutter 3.16.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 41456452f2 (12 days ago) • 2024-01-25 10:06:23 -0800
Engine • revision f40e976bed
Tools • Dart 3.2.6 • DevTools 2.28.5

**Comment by evil159** [comment]
@Cernius Check that you have the correct token setup in your `~/.netrc` file as per https://github.com/mapbox/mapbox-maps-flutter?tab=readme-ov-file#configure-credentials. Likely the module can't be resolved because Cocoapods couldn't pull the binary dependency in.

**Comment by Cernius** [comment]
Hey @evil159. Yes I set up the `~/.netrc` the same as in example, using my credentials of course. When the file `~/.netrc`
isn't set up correctly I think you just get this error : The requested URL returned error: 401.

**Comment by Cernius** [comment]
The problem was with coacoapods version 1.15.1. I've downgraded it to 1.14.3 and now it works fine
