### ISSUE TITLE
Style layers influenced by the light settings in Mapbox Standard

### ISSUE THREAD

**Issue by ramonespmat** [mapbox/mapbox-maps-flutter#404]
I want to display some clusters with points from a GeoJSON (as the available example) and as i am using the Dark light setting of Mapbox Standard the clusters appear excessively dark (i almost cannot see them). 

Is there a way of making the layer independent of the standard style? Or is there another possible aproach?

Thanks!

**Comment by ramonespmat** [comment]
Thanks for your response Baleboy!

It helped me a lot to know what to do but i cannot get it to work as I need. I tried two different approaches.

APPROACH 1:
 
If I add a layer like this (as in the cluster example):

```
    var layer =
        await rootBundle.loadString('assets/cluster/cluster_layer.json');
    mapboxMap?.style.addStyleLayer(layer, null);
        
```
        
I do not know how to set the emissive strength to 1, is that set on the cluster_layer.json?
   
APPROACH 2:

And if i add the clustering with the CircleLayer class (where i can set the emissive strength to 1), i cannot set the filter as defined on cluster_layer.json on the approach 1 to make the clusters disappear when containing just one point. 

cluster_layer.json

```
{
    "id": "cluster-count",
    "type": "symbol",
    "source": "earthquakes",
    "filter": [
      "has",
      "point_count"
    ],
```
Second approach layer definition:

```
  void _addClusterCircleLayer2() async {

    var geoJsonSource = GeoJsonSource(
      id: 'earthquakes',
      data: "https://docs.mapbox.com/mapbox-gl-js/assets/earthquakes.geojson",
      cluster: true,
      clusterMaxZoom: 14,
      clusterRadius: 50,
    );

    mapboxMap?.style.addSource(geoJsonSource);

    CircleLayer circleLayer = CircleLayer(
      id: 'cluster-circle-layer', 
      sourceId: 'earthquakes', 
      circleColor: Color.fromARGB(255, 255, 0, 0).value, 
      circleRadius: 15.0, 
      circleEmissiveStrength: 1.0, 
    );
    mapboxMap?.style.addLayer(circleLayer);
  }
```

**Comment by maxiggle** [comment]
@baleboy @ramonespmat  I know this is closed but I need help
I have clusters and markers defined on my map in the standard style, but when I switch to satellite view, my data is lost and it throws errors like below:
Please let me know if my question is not clear
```[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(0, MapError(errorDescription: "Source \'earthquakes\' does not exist."), null, null)```
