### ISSUE TITLE
Clustering Annotations

### ISSUE THREAD

**Issue by FarisArmoush** [mapbox/mapbox-maps-flutter#416]
Currently in my app im using Mapbox's point annotations to display data on the map, and mostly this data will always be in the same city, so what I want to do is that when I zoom out, I want the data within the same range to be clustered/grouped into one single annotation.

note: I did see the example of clusters, but I couldn't figure out how to implement it with annotations.

```dart
  PointAnnotation? pointAnnotation;
  PointAnnotationManager? pointAnnotationManager;
  void setMapController(MapboxMap newController) {
    this.mapController = newController;
   _addGraphics();
  }
  void _addGraphics() {
    mapController?.annotations
        .createPointAnnotationManager()
        .then((manager) async {
      pointAnnotationManager = manager;

      final mapMarkerBytes = await rootBundle.load(ConstImages.mapMarker);
      final mapMarker = mapMarkerBytes.buffer.asUint8List();

      final viewedMarkerBytes = await rootBundle.load(ConstImages.viewedMarker);
      final viewedMarker = viewedMarkerBytes.buffer.asUint8List();

      final options = <PointAnnotationOptions>[];
      realEstates.state?.forEach((RealEstate element) {
        final bool isViewed = element.isViewed ?? false;
        final point = Point(
          coordinates: Position(
            element.longitude ?? 46.6753,
            element.latitude ?? 24.7136,
          ),
        ).toJson();
        final map = {
          ...point,
          'ad_id': element.id,
        };
        final formatter = NumberFormat.compactCurrency(
          decimalDigits: 2,
          symbol: '',
        );
        options.add(
          PointAnnotationOptions(
            geometry: map,
            iconSize: 1,
            image: isViewed ? viewedMarker : mapMarker,
            textSize: 14,
            textColor: Colors.white.value,
            textJustify: TextJustify.CENTER,
            textAnchor: TextAnchor.CENTER,
            textField: formatter.format(
              element.theSubTypeOfAd == 'rent'
                  ? int.tryParse(element.rentalPrice.toString()) ?? 0
                  : int.tryParse(element.sellingPrice.toString()),
            ),
          ),
        );

        pointAnnotationManager?.addOnPointAnnotationClickListener(
          AnnotationClickListener(),
        );
      });
      await pointAnnotationManager?.createMulti(options);
    });
  }
```

**Comment by HenrikH96** [comment]
@FarisArmoush 
I stumbled upon the same problem. Have you figured it out? Furthermore, I tried your 'trick' to append custom data to the geometry part of the Point Annotation, but it doesn't work for me. If you've found a solution, would it be possible to share it? My field is always null despite setting it up like you did.

```
class AnnotationClickListener extends OnPointAnnotationClickListener {
  @override
  void onPointAnnotationClick(PointAnnotation annotation) {
    print("onAnnotationClick, id: ${annotation.geometry!["ad_id"]}");
  }
}
```

It would be super helpful!

**Comment by FarisArmoush** [comment]
> @FarisArmoush 
> 
> I stumbled upon the same problem. Have you figured it out? Furthermore, I tried your 'trick' to append custom data to the geometry part of the Point Annotation, but it doesn't work for me. If you've found a solution, would it be possible to share it? My field is always null despite setting it up like you did.
> 
> 
> 
> ```
> 
> class AnnotationClickListener extends OnPointAnnotationClickListener {
> 
>   @override
> 
>   void onPointAnnotationClick(PointAnnotation annotation) {
> 
>     print("onAnnotationClick, id: ${annotation.geometry!["ad_id"]}");
> 
>   }
> 
> }
> 
> ```
> 
> 
> 
> It would be super helpful! 

Unfortunately i couldnt find a solution so me and my team had to figure out a different solution where we fetch a specific amount of data on each zoom level. I figured there was no way this solution could be implemented with the mapbox flutter SDK so we had to think out of the box.

**Comment by HenrikH96** [comment]
@FarisArmoush thanks for the quick response. 
That's a bummer. Than I have to figure out something on my own :/

**Comment by FarisArmoush** [comment]
> @FarisArmoush thanks for the quick response. 
> 
> That's a bummer. Than I have to figure out something on my own :/ 
> 
> 

Hopefully with more enhancements, better documentation, and more features this Mapbox SDK would be very OP.
