### ISSUE TITLE
401 Unauthorized when building Android appbundle using v1.0.0

### ISSUE THREAD

**Issue by nicolamazz** [mapbox/mapbox-maps-flutter#428]
I am trying to build the appbundle of my app using the new Mapbox 1.0.0 but I am getting 401: Unauthorized.

`
Execution failed for task ':app:checkReleaseDuplicateClasses'.
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve com.mapbox.maps:android:11.2.0.
     Required by:
         project :app > project :mapbox_maps_flutter
      > Could not resolve com.mapbox.maps:android:11.2.0.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/maps/android/11.2.0/android-11.2.0.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/maps/android/11.2.0/android-11.2.0.pom'. Received status code 401 from server: Unauthorized
`

I tried using the previous version 0.5.1 and it is building without problems.

**Comment by Nortontium** [comment]
Same error here. Putting SDK_REGISTRY_TOKEN=YOUR_SECRET_TOKEN into top level gradle.properties instead of .gradle/gradle.properties (as the documentation says) fixed it for me.

**Comment by ma-ben10** [comment]
same error any suggestions for it : 
Could not resolve com.mapbox.maps:android:11.2.0.
