### ISSUE TITLE
Could not find module 'MapboxMaps' for target 'arm64-apple-ios-simulator'

### ISSUE THREAD

**Issue by resfandiari** [mapbox/mapbox-maps-flutter#43]
Apple silicon m1
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.73.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by kamami** [comment]
I am able to run the iOS Simulator on my M1 Macbook without issues.

**Comment by Thomas-ARKADY** [comment]
<img width="1125" alt="Capture d’écran 2023-01-20 à 12 16 12" src="https://user-images.githubusercontent.com/118881483/213682788-70f23b3f-3585-4e73-b5d4-a76a4deb541c.png">
Same on M1 pro

**Comment by resfandiari** [comment]
> I am able to run the iOS Simulator on my M1 Macbook without issues.

Are you able to create simple projects on Github?

**Comment by resfandiari** [comment]
> <img alt="Capture d’écran 2023-01-20 à 12 16 12" width="1125" src="https://user-images.githubusercontent.com/118881483/213682788-70f23b3f-3585-4e73-b5d4-a76a4deb541c.png">
> 
> Same on M1 pro

Rosetta needs to be up-to-date, and Xcode needs to be run with it.

**Comment by rtviwe** [comment]
@resfandiari how did you fixed the problem? Running Xcode like that `arch -x86_64 /Applications/Xcode.app/Contents/MacOS/Xcode` and thats all?

**Comment by resfandiari** [comment]
> @resfandiari how did you fixed the problem? Running Xcode like that `arch -x86_64 /Applications/Xcode.app/Contents/MacOS/Xcode` and thats all?

I only updated Rosetta and set up Xcode to run with it, and the project's example ran without any issues
https://community.appdynamics.com/t5/Knowledge-Base/How-do-I-run-the-iOS-simulator-on-my-M1-based-Mac/ta-p/46825

**Comment by blk-raffy** [comment]
<img width="203" alt="Screenshot 2024-01-29 alle 09 39 00" src="https://github.com/mapbox/mapbox-maps-flutter/assets/34171011/7803d288-e596-4776-a303-80986f71fa13">

Seems like xcode doesn't have "Open with Rosetta" anymore, any workaround? (I have Rosetta installed because on Safari or other apps I see the flag)
