### ISSUE TITLE
[Build Error]: Failed to notify project evaluation listener.

### ISSUE THREAD

**Issue by singhayush20** [mapbox/mapbox-maps-flutter#434]
1. I added the package with the command-  `flutter pub add mapbox_maps_flutter` (version ^1.0.0)
2. Build the project 
3. Error when building the project-  
[build error.txt](https://github.com/mapbox/mapbox-maps-flutter/files/14534080/build.error.txt)

4. My build.gradle-

buildscript {
    ext.kotlin_version = '1.7.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

**Comment by evil159** [comment]
Hi @singhayush20, in the error log you've attached I can see `> SDK Registry token is null. See README.md for more information.`
It seems that your SDK_REGISTRY_TOKEN in not configured properly, please refer to https://github.com/mapbox/mapbox-maps-flutter?tab=readme-ov-file#secret-token for more information on this.
I'm closing this issue, feel free to reopen if you have more feedback.
