### ISSUE TITLE
NSLocationWhenInUseUsageDescription required even if not used

### ISSUE THREAD

**Issue by martinfrouin** [mapbox/mapbox-maps-flutter#447]
I just got an email from Apple which ask me to add location permissions on the info.plist file, but I don't use it on the map.
Is there any solution to disable it and avoid to set theses lines for nothing ?

> ITMS-90683: Missing purpose string in Info.plist
> ... should contain a NSLocationAlwaysAndWhenInUseUsageDescription key
> ... should contain a NSLocationWhenInUseUsageDescription key

**Comment by maios** [comment]
Hi @martinfrouin, if your app or any of the frameworks that your app is linked to, has source code to access user's location then you must provide location usage description eventhough your app does not access them. 

> Starting spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string.If you're using external libraries or SDKs, they may reference APIs that require a purpose string. **_While your app might not use these APIs, a purpose string is still required_**. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs.

**Comment by deandreamatias-worldline** [comment]
@maios this don't make sense. The plugin should disabled permissions that not use.
Maybe this issue can help https://github.com/Baseflow/flutter-permission-handler/issues/1160

**Comment by deandreamatias-worldline** [comment]
I have an error that Apple detect a issue because my app use `NSLocationAlwaysAndWhenInUseUsageDescription` but isn't declared on Info.plist. But I don't really use this permission, only use `NSLocationWhenInUseUsageDescription`
