### ISSUE TITLE
[BUG] Map still appear for less than a sec after I close the page.

### ISSUE THREAD

**Issue by flaviopopoff** [mapbox/mapbox-maps-flutter#453]
Hi guys!
I am facing this issue with the v1.0.0, I open a page in my app with the map, after I close this page and the map still appears for less than a second.

How I can resolve this? After the close of the page I have an error that told me that I am using the map after the dispose.

https://github.com/mapbox/mapbox-maps-flutter/assets/59371153/91b12d22-4488-4454-ac6c-c2936a367d0d

Code example
```dart
Future<void> main() async {

  MapboxOptions.setAccessToken(dotenv.env['MAPBOX']!);
  runApp(const ProviderScope(child: App()));
}


class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Home()
    );
  }
}


class Home extends StatelessWidget {
  const Home({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: IconButton(
          icon: const Icon(Icons.open_in_full),
          onPressed: () {
            Navigator.push(context, MaterialPageRoute(builder: (ctx) => const ExampleMap()));
          },
        ),
      ),
    );
  }
}


class ExampleMap extends StatefulWidget {
  const ExampleMap({super.key});

  @override
  State<ExampleMap> createState() => _ExampleMapState();
}

class _ExampleMapState extends State<ExampleMap> {

  MapboxMap? mapbox;

  @override
  void dispose() {
    mapbox?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: MapWidget(
          onMapCreated: (MapboxMap map) async {
            mapbox = map;
          },
        )
      ),
    );
  }
}
```

**Comment by evil159** [comment]
Hi @flaviopopoff, thank you for the detailed report! 

I have two suggestions for you:
* No need to call `dispose()` manually - it is being called automatically by Flutter
*  Try configuring map widget with the Virtual Display(VD) platform view hosting mode - default hosting mode on Android is Hybrid Composition in v1, in our experience VD behaves nicer when a platform view being dismissed.
```dart
MapWidget(
  androidHostingMode: AndroidPlatformViewHostingMode.VD,
)
```

You can read more about advantages and disadvantages of Android platform view hosting modes in [this article](https://github.com/flutter/flutter/wiki/Android-Platform-Views).

**Comment by flaviopopoff** [comment]
@evil159 thanks for your respond, it's working fine, thanks!
