### ISSUE TITLE
Point annotations are now broken

### ISSUE THREAD

**Issue by ristiisa** [mapbox/mapbox-maps-flutter#457]
@evil159 starting from your commit 06cbea788f2a965246207d4c012bea11b6b8e2fa the point annotations that display an image are broken. Please check the examples app on IOS.

before:
<img width="262" alt="image" src="https://github.com/mapbox/mapbox-maps-flutter/assets/514571/2f30264f-7927-4d27-8a91-be4f399a6781">

after:
<img width="292" alt="image" src="https://github.com/mapbox/mapbox-maps-flutter/assets/514571/27ec1fe0-c185-473a-9599-7a876d7c0615">

**Comment by ristiisa** [comment]
@evil159 
@maios 
@pjleonard37
@ThibaudLopez

Any insight?

**Comment by evil159** [comment]
Hi @ristiisa, thank you for reporting this, I can confirm that issue reproducing on my side as well, internal ticket to track this - https://mapbox.atlassian.net/issues/MAPSFLT-196.

**Comment by ristiisa** [comment]
confirming that it is fixed, thank you @evil159
