### ISSUE TITLE
Can I set a min/max zoom for the camera?

### ISSUE THREAD

**Issue by AnEpicName** [mapbox/mapbox-maps-flutter#46]
I want to have a limit for the camera zoom, something like `maxZoom = 20` and `minZoom = 7`.

So far I've forced this behaviour in the `onCameraChangeListener` event by doing this:
```dart
 await mapboxMap!.getCameraState().then((value) {
            if (zoom >= minZoom) {
              zoom = value.zoom;
            } else {
              zoom = minZoom;
              mapboxMap!.setCamera(CameraOptions(zoom: minZoom));
            }
          });
```
But it doesn't feel "clean", because every time I try to go over the threshold, the map starts to "vibrate". Is there a better way to do this? Or am I missing something?

**Comment by LjubiTech-Maxko** [comment]
Try this

```
await _mapboxMap!.setBounds(CameraBoundsOptions(
  maxZoom: maxZoom,
  minZoom: minZoom,
));
```

**Comment by AnEpicName** [comment]
Exactly what I needed! Thanks!
