### ISSUE TITLE
MapWidget.cameraOptions are serialized as a List but deserialized as Dict

### ISSUE THREAD

**Issue by ristiisa** [mapbox/mapbox-maps-flutter#464]
It seems that starting with commit https://github.com/mapbox/mapbox-maps-flutter/commit/06cbea788f2a965246207d4c012bea11b6b8e2fa more things are broken...

The data structure that the swift side expect is different than the flutter side passes on. At the end cameraOptions are not used for initializing the map.

<img width="251" alt="image" src="https://github.com/mapbox/mapbox-maps-flutter/assets/514571/cbaf66ae-b02e-4a74-ab9a-17c4162c6156">

https://github.com/mapbox/mapbox-maps-flutter/blob/main/lib/src/pigeons/map_interfaces.dart#L472 ->
<img width="221" alt="image" src="https://github.com/mapbox/mapbox-maps-flutter/assets/514571/720894c1-4589-4d4f-85f0-a83da38d39c4">
https://github.com/mapbox/mapbox-maps-flutter/blob/main/lib/src/turf_adapters.dart#L17 ->

<img width="638" alt="image" src="https://github.com/mapbox/mapbox-maps-flutter/assets/514571/62b89b82-c16b-492c-b263-adaea515a5d9">

https://github.com/mapbox/mapbox-maps-flutter/blob/main/ios/Classes/MapboxMapFactory.swift#L88

**Comment by evil159** [comment]
@ristiisa Thank you for the report! This issue should be fixed in #469, I'm closing this ticket, feel free to reopen if there is more to it.
