### ISSUE TITLE
🐛 Plugin crashing the app since 1.0.0

### ISSUE THREAD

**Issue by tempo-riz** [mapbox/mapbox-maps-flutter#465]
Hello, everything was fine in version 0.5.1
We upgraded to 1.0.0

On iOS:
On navigating with go router to a simple other route (see video)
The following errors occurs on iOS and crash the app without more logs:
MapboxMaps/MapView.swift:589: Assertion failed
could be related to this :
https://github.com/mapbox/mapbox-maps-ios/issues/2154

On Android:
we have some weird flickering since the upgrade : 
even if there is no map showing in the record I can assure you it's coming from this upgrade (It was tested changing only the dependency version)

https://github.com/mapbox/mapbox-maps-flutter/assets/64015162/6c058508-6060-42bc-b7d4-7516829782dc

**Comment by baleboy** [comment]
Thanks for the report. As we haven't seen this issue in our tests, would you be able to provide a sample project that reproduces it?

**Comment by evil159** [comment]
@tempo-riz Thank you for the reports:
* Indeed, the iOS behavior is fixed in the iOS SDK and is available in v1.1.0-rc.1 that will be released today
* As for the flickering on Android - could you try changing the hosting mode to see if it helps?

**Comment by tempo-riz** [comment]
Thanks for the quick reply !
Okay so I tried to use the following AndroidPlatformViewHostingMode
- HC 
- TLHC_HC 
- TLHC_VD 
- VD

So it seems the .HC default mode is the only one causing flickers 
Tbh I am a bit clueless about the meaning of those rendering options and their implications :)

**Comment by evil159** [comment]
@tempo-riz You can read more about Android Platform Views hosting modes in Flutter [here](https://github.com/flutter/flutter/wiki/Android-Platform-Views).

Recently, we have changed hosting mode to HC because of a bug in Flutter - https://github.com/flutter/flutter/issues/142978. Previously, we relied on VD, so you should be safe to switch to VD after the fix for Flutter engine is released.

**Comment by evil159** [comment]
1.1.0-rc.1 is [released](https://github.com/mapbox/mapbox-maps-flutter/releases/tag/v1.1.0-rc.1), I'm closing this, feel free to reopen if there is more to be done here, thank you!
