### ISSUE TITLE
Updating mapbox-maps-ios to 10.17.0

### ISSUE THREAD

**Issue by aamirki** [mapbox/mapbox-maps-flutter#475]
May 1st is the deadline to have a proper privacy manifest on iOS to be able to release updates to apps which use this package, https://github.com/mapbox/mapbox-maps-ios/issues/2145 details the issue and it seems like the fix was released as part of mapbox-maps-ios 10.17.0

**Comment by evil159** [comment]
Hi @aamirki, this will be released as a part of Mapbox Maps Flutter Plugin v1.1.0, you can adopt it early with the release candidate https://github.com/mapbox/mapbox-maps-flutter/releases/tag/v1.1.0-rc.1. Stable release should land next week. Would this timeline work for you?

**Comment by aamirki** [comment]
Thank you @evil159 that's perfect!
