### ISSUE TITLE
1.1.0-rc.1  crashes on Android

### ISSUE THREAD

**Issue by autolainen** [mapbox/mapbox-maps-flutter#477]
I am trying to setup just a basic map view and when a route with map open, all the app crashes with stacktrace:

E/ThemeUtils(21728): View class com.mapbox.maps.plugin.compass.CompassViewImpl is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
E/ThemeUtils(21728): View class com.mapbox.maps.plugin.logo.LogoViewImpl is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
E/ThemeUtils(21728): View class com.mapbox.maps.plugin.attribution.AttributionViewImpl is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
I/PlatformViewsController(21728): Using hybrid composition for platform view: 0
D/TrafficStats(21728): tagSocket(239) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats(21728): tagSocket(220) with statsTag=0xffffffff, statsUid=-1
D/CompatibilityChangeReporter(21728): Compat change id reported: 236825255; UID 10275; state: DISABLED
E/flutter (21728): [ERROR:flutter/fml/platform/android/jni_util.cc(206)] java.lang.IllegalStateException: Please ensure that the hosting activity/fragment is a valid LifecycleOwner
E/flutter (21728): 	at com.mapbox.maps.plugin.lifecycle.ViewLifecycleOwner.doOnAttached(ViewLifecycleOwner.kt:70)
E/flutter (21728): 	at com.mapbox.maps.plugin.lifecycle.ViewLifecycleOwner.<init>(ViewLifecycleOwner.kt:60)
E/flutter (21728): 	at com.mapbox.maps.plugin.lifecycle.MapboxLifecyclePluginImpl.registerLifecycleObserver(MapboxLifecyclePluginImpl.kt:30)
E/flutter (21728): 	at com.mapbox.maps.plugin.MapPluginRegistry.onAttachedToWindow(MapPluginRegistry.kt:192)
E/flutter (21728): 	at com.mapbox.maps.MapController.onAttachedToWindow$sdk_release(MapController.kt:366)
E/flutter (21728): 	at com.mapbox.maps.MapView.onAttachedToWindow(MapView.kt:135)
E/flutter (21728): 	at android.view.View.dispatchAttachedToWindow(View.java:23198)
E/flutter (21728): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3694)
E/flutter (21728): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3701)
E/flutter (21728): 	at android.view.ViewGroup.addViewInner(ViewGroup.java:5548)
E/flutter (21728): 	at android.view.ViewGroup.addView(ViewGroup.java:5324)
E/flutter (21728): 	at android.view.ViewGroup.addView(ViewGroup.java:5264)
E/flutter (21728): 	at android.view.ViewGroup.addView(ViewGroup.java:5236)
E/flutter (21728): 	at io.flutter.plugin.platform.PlatformViewsController.initializePlatformViewIfNeeded(PlatformViewsController.java:1128)
E/flutter (21728): 	at io.flutter.plugin.platform.PlatformViewsController.onDisplayPlatformView(PlatformViewsController.java:1158)
E/flutter (21728): 	at io.flutter.embedding.engine.FlutterJNI.onDisplayPlatformView(FlutterJNI.java:1462)
E/flutter (21728): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (21728): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (21728): 	at android.os.Looper.loopOnce(Looper.java:187)
E/flutter (21728): 	at android.os.Looper.loop(Looper.java:319)
E/flutter (21728): 	at android.app.ActivityThread.main(ActivityThread.java:8893)
E/flutter (21728): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (21728): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
E/flutter (21728): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
E/flutter (21728): 
F/flutter (21728): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1696)] Check failed: fml::jni::CheckException(env). 
F/libc    (21728): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 21728 (est.client.test), pid 21728 (est.client.test)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/o1sxser/o1s:14/UP1A.231005.007/G991BXXS9FXBE:user/release-keys'
Revision: '22'
ABI: 'arm64'
Processor: '7'
Timestamp: 2024-04-08 15:28:14.324202753+0300
Process uptime: 18s
Cmdline: io.deliverest.client.test
pid: 21728, tid: 21728, name: est.client.test  >>> io.deliverest.client.test <<<
uid: 10275
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1696)] Check failed: fml::jni::CheckException(env). '
    x0  0000000000000000  x1  00000000000054e0  x2  0000000000000006  x3  0000007fe5727e10
    x4  6d602e6c716e6573  x5  6d602e6c716e6573  x6  6d602e6c716e6573  x7  7f7f7f7f7f7f7f7f
    x8  00000000000000f0  x9  0000007e6b4761e8  x10 0000000000000001  x11 0000007e6b4bc230
    x12 0000000000009f35  x13 0000000000000000  x14 0000007fe5726cc0  x15 0000000026762762
    x16 0000007e6b520d08  x17 0000007e6b4fe0f0  x18 0000007e76a3a000  x19 00000000000054e0
    x20 00000000000054e0  x21 00000000ffffffff  x22 b400007cb3c967b0  x23 b400007d93d18a18
    x24 000000000000008c  x25 00000000000007a4  x26 0000000000000000  x27 0000007fe5728108
    x28 0000007e76b65039  x29 0000007fe5727e90
    lr  0000007e6b4adb8c  sp  0000007fe5727df0  pc  0000007e6b4adbb8  pst 0000000000001000
61 total frames
backtrace:
      #00 pc 0000000000059bb8  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: 2febda0bbcffa4b71545deb95b27767d)
      #01 pc 0000000001c88650  /data/app/~~H4IlOE2NSWrtfOfibddrqw==/io.deliverest.client.test-yEFmyPHJcYS5QYnhoOgX9A==/base.apk!libflutter.so (offset 0xf090000) (BuildId: 4d97602cbbe2c28cc90c771860f5810a6e9ec76b)
      #02 pc 0000000001cb25e0  /data/app/~~H4IlOE2NSWrtfOfibddrqw==/io.deliverest.client.test-yEFmyPHJcYS5QYnhoOgX9A==/base.apk!libflutter.so (offset 0xf090000) (BuildId: 4d97602cbbe2c28cc90c771860f5810a6e9ec76b)
      #03 pc 0000000001c975ec  /data/app/~~H4IlOE2NSWrtfOfibddrqw==/io.deliverest.client.test-yEFmyPHJcYS5QYnhoOgX9A==/base.apk!libflutter.so (offset 0xf090000) (BuildId: 4d97602cbbe2c28cc90c771860f5810a6e9ec76b)
      #04 pc 000000000242baa4  /data/app/~~H4IlOE2NSWrtfOfibddrqw==/io.deliverest.client.test-yEFmyPHJcYS5QYnhoOgX9A==/base.apk!libflutter.so (offset 0xf090000) (BuildId: 4d97602cbbe2c28cc90c771860f5810a6e9ec76b)
      #05 pc 00000000020cedcc  /data/app/~~H4IlOE2NSWrtfOfibddrqw==/io.deliverest.client.test-yEFmyPHJcYS5QYnhoOgX9A==/base.apk!libflutter.so (offset 0xf090000) (BuildId: 4d97602cbbe2c28cc90c771860f5810a6e9ec76b)
      #06 pc 00000000020ce88c  /data/app/~~H4IlOE2NSWrtfOfibddrqw==/io.deliverest.client.test-yEFmyPHJcYS5QYnhoOgX9A==/base.apk!libflutter.so (offset 0xf090000) (BuildId: 4d97602cbbe2c28cc90c771860f5810a6e9ec76b)
      #07 pc 00000000020cd8ec  /data/app/~~H4IlOE2NSWrtfOfibddrqw==/io.deliverest.client.test-yEFmyPHJcYS5QYnhoOgX9A==/base.apk!libflutter.so (offset 0xf090000) (BuildId: 4d97602cbbe2c28cc90c771860f5810a6e9ec76b)
      #08 pc 00000000020ce118  /data/app/~~H4IlOE2NSWrtfOfibddrqw==/io.deliverest.client.test-yEFmyPHJcYS5QYnhoOgX9A==/base.apk!libflutter.so (offset 0xf090000) (BuildId: 4d97602cbbe2c28cc90c771860f5810a6e9ec76b)
      #09 pc 00000000020cf604  /data/app/~~H4IlOE2NSWrtfOfibddrqw==/io.deliverest.client.test-yEFmyPHJcYS5QYnhoOgX9A==/base.apk!libflutter.so (offset 0xf090000) (BuildId: 4d97602cbbe2c28cc90c771860f5810a6e9ec76b)
      #10 pc 00000000020cdcdc  /data/app/~~H4IlOE2NSWrtfOfibddrqw==/io.deliverest.client.test-yEFmyPHJcYS5QYnhoOgX9A==/base.apk!libflutter.so (offset 0xf090000) (BuildId: 4d97602cbbe2c28cc90c771860f5810a6e9ec76b)
      #11 pc 00000000020cdaa4  /data/app/~~H4IlOE2NSWrtfOfibddrqw==/io.deliverest.client.test-yEFmyPHJcYS5QYnhoOgX9A==/base.apk!libflutter.so (offset 0xf090000) (BuildId: 4d97602cbbe2c28cc90c771860f5810a6e9ec76b)
      #12 pc 0000000001cb3188  /data/app/~~H4IlOE2NSWrtfOfibddrqw==/io.deliverest.client.test-yEFmyPHJcYS5QYnhoOgX9A==/base.apk!libflutter.so (offset 0xf090000) (BuildId: 4d97602cbbe2c28cc90c771860f5810a6e9ec76b)
      #13 pc 0000000001cb8c20  /data/app/~~H4IlOE2NSWrtfOfibddrqw==/io.deliverest.client.test-yEFmyPHJcYS5QYnhoOgX9A==/base.apk!libflutter.so (offset 0xf090000) (BuildId: 4d97602cbbe2c28cc90c771860f5810a6e9ec76b)
      #14 pc 0000000000018300  /system/lib64/libutils.so (android::Looper::pollInner(int)+1248) (BuildId: 349e8a707584d82e0226d35def83e3d0)
      #15 pc 0000000000017dc0  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+120) (BuildId: 349e8a707584d82e0226d35def83e3d0)
      #16 pc 0000000000184494  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44) (BuildId: 4b6c592933d9e19dac2d846de01f461b)
      #17 pc 0000000000351e30  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+144) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #18 pc 000000000033b3a4  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #19 pc 0000000000511590  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, bool, art::JValue*)+1976) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #20 pc 0000000000491434  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>(art::interpreter::SwitchImplContext*)+2092) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #21 pc 00000000003545d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #22 pc 0000000000238ca0  /system/framework/framework.jar (android.os.MessageQueue.next+0)
      #23 pc 000000000036e6ec  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.__uniq.112435418011751916792819755956732575238.llvm.15516541934131658184)+232) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #24 pc 000000000051225c  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, bool, art::JValue*)+5252) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #25 pc 0000000000490ffc  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>(art::interpreter::SwitchImplContext*)+1012) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #26 pc 00000000003545d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #27 pc 0000000000237b88  /system/framework/framework.jar (android.os.Looper.loopOnce+0)
      #28 pc 000000000036e6ec  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.__uniq.112435418011751916792819755956732575238.llvm.15516541934131658184)+232) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #29 pc 000000000051225c  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, bool, art::JValue*)+5252) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #30 pc 000000000049136c  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>(art::interpreter::SwitchImplContext*)+1892) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #31 pc 00000000003545d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #32 pc 00000000002383c4  /system/framework/framework.jar (android.os.Looper.loop+0)
      #33 pc 000000000036e6ec  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.__uniq.112435418011751916792819755956732575238.llvm.15516541934131658184)+232) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #34 pc 000000000051225c  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, bool, art::JValue*)+5252) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #35 pc 000000000049136c  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>(art::interpreter::SwitchImplContext*)+1892) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #36 pc 00000000003545d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #37 pc 00000000001d2034  /system/framework/framework.jar (android.app.ActivityThread.main+0)
      #38 pc 000000000036e6ec  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.__uniq.112435418011751916792819755956732575238.llvm.15516541934131658184)+232) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #39 pc 000000000036dfe4  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+964) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #40 pc 0000000000351f68  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #41 pc 000000000033b680  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+640) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #42 pc 000000000037cb18  /apex/com.android.art/lib64/libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1556) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #43 pc 000000000037c4f4  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*) (.__uniq.165753521025965369065708152063621506277)+32) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #44 pc 0000000000351e30  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+144) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #45 pc 000000000033b3a4  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #46 pc 0000000000511590  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, bool, art::JValue*)+1976) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #47 pc 0000000000490ffc  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>(art::interpreter::SwitchImplContext*)+1012) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #48 pc 00000000003545d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #49 pc 000000000026b30c  /system/framework/framework.jar (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+0)
      #50 pc 000000000036e6ec  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.__uniq.112435418011751916792819755956732575238.llvm.15516541934131658184)+232) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #51 pc 000000000036dfe4  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+964) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #52 pc 0000000000351f68  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #53 pc 0000000000da3e04  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (com.android.internal.os.ZygoteInit.main+3604)
      #54 pc 000000000033b680  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+640) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #55 pc 00000000004e2a90  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+728) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #56 pc 000000000057aa68  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+156) (BuildId: 4801adadf1dae7e020ba05f3204efc9c)
      #57 pc 00000000000deab4  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+104) (BuildId: 4b6c592933d9e19dac2d846de01f461b)
      #58 pc 00000000000eaf58  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+852) (BuildId: 4b6c592933d9e19dac2d846de01f461b)
      #59 pc 0000000000002550  /system/bin/app_process64 (main+1276) (BuildId: a44f122a988065284d391c467ea337f2)
      #60 pc 0000000000052714  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+104) (BuildId: 2febda0bbcffa4b71545deb95b27767d)
Lost connection to device.

**Comment by evil159** [comment]
@autolainen Thank you for making the report, could you attach a sample project where this issue could be reproduced?

**Comment by evil159** [comment]
Hi all, this issue should be fixed in https://github.com/mapbox/mapbox-maps-flutter/pull/478, feel free to reopen this ticket if you have any feedback!
