### ISSUE TITLE
Launch app with other mapbox plugin

### ISSUE THREAD

**Issue by artemsorochan** [mapbox/mapbox-maps-flutter#50]
If in addition to mapbox_maps_flutter add another mapbox plugin(in my case flutter_mapbox_navigation) it throws this error.
Any idea on what might be done to fix it would be highly appreciated. Thanks.

E/AndroidRuntime( 5233): java.lang.IllegalStateException: Please ensure that the hosting activity/fragment is a valid LifecycleOwner
E/AndroidRuntime( 5233): 	at com.mapbox.maps.plugin.lifecycle.ViewLifecycleOwner.doOnAttached(ViewLifecycleOwner.kt:68)
E/AndroidRuntime( 5233): 	at com.mapbox.maps.plugin.lifecycle.ViewLifecycleOwner.<init>(ViewLifecycleOwner.kt:58)
E/AndroidRuntime( 5233): 	at com.mapbox.maps.plugin.lifecycle.MapboxLifecyclePluginImpl.registerLifecycleObserver(MapboxLifecyclePluginImpl.kt:30)
E/AndroidRuntime( 5233): 	at com.mapbox.maps.plugin.MapPluginRegistry.onAttachedToWindow(MapPluginRegistry.kt:173)
E/AndroidRuntime( 5233): 	at com.mapbox.maps.MapController.onAttachedToWindow$sdk_release(MapController.kt:333)
E/AndroidRuntime( 5233): 	at com.mapbox.maps.MapView.onAttachedToWindow(MapView.kt:115)
E/AndroidRuntime( 5233): 	at android.view.View.dispatchAttachedToWindow(View.java:21291)

**Comment by evil159** [comment]
Hi, this issue should be fixed in https://github.com/mapbox/mapbox-maps-flutter/pull/478, feel free to reopen this ticket if you have any feedback!
