### ISSUE TITLE
How to fix this exception? no ES 3 support?

### ISSUE THREAD

**Issue by ember11498** [mapbox/mapbox-maps-flutter#504]
I got this error:

    E/EGL_emulation(18317): eglCreateContext: EGL_BAD_CONFIG: no ES 3 support
    E/EGL_emulation(18317): tid 18512: eglCreateContext(1682): error 0x3005 (EGL_BAD_CONFIG)
    E/AndroidRuntime(18317): FATAL EXCEPTION: MapboxRenderThread
    E/AndroidRuntime(18317): Process: com.example.temp, PID: 18317
    E/AndroidRuntime(18317): java.lang.IllegalStateException: OpenGL ES 3.0 context could not be created
    E/AndroidRuntime(18317): 	at com.mapbox.maps.renderer.egl.EGLCore.prepareEgl(EGLCore.kt:89)
    E/AndroidRuntime(18317): 	at com.mapbox.maps.renderer.MapboxRenderThread.checkEglConfig(MapboxRenderThread.kt:246)
    E/AndroidRuntime(18317): 	at com.mapbox.maps.renderer.MapboxRenderThread.setUpRenderThread(MapboxRenderThread.kt:207)
    E/AndroidRuntime(18317): 	at com.mapbox.maps.renderer.MapboxRenderThread.prepareRenderFrame(MapboxRenderThread.kt:459)
    E/AndroidRuntime(18317): 	at com.mapbox.maps.renderer.MapboxRenderThread.processAndroidSurface$sdk_release(MapboxRenderThread.kt:542)
    E/AndroidRuntime(18317): 	at com.mapbox.maps.renderer.MapboxRenderThread$onSurfaceCreated$1$1$1.invoke(MapboxRenderThread.kt:559)
    E/AndroidRuntime(18317): 	at com.mapbox.maps.renderer.MapboxRenderThread$onSurfaceCreated$1$1$1.invoke(MapboxRenderThread.kt:558)
    E/AndroidRuntime(18317): 	at com.mapbox.maps.renderer.RenderHandlerThread.postDelayed$lambda$1$lambda$0(RenderHandlerThread.kt:39)
    E/AndroidRuntime(18317): 	at com.mapbox.maps.renderer.RenderHandlerThread.$r8$lambda$YB_YSeUrlxhPn95u2dpCGDwyAyU(Unknown Source:0)
    E/AndroidRuntime(18317): 	at com.mapbox.maps.renderer.RenderHandlerThread$$ExternalSyntheticLambda0.run(Unknown Source:2)
    E/AndroidRuntime(18317): 	at android.os.Handler.handleCallback(Handler.java:938)
    E/AndroidRuntime(18317): 	at android.os.Handler.dispatchMessage(Handler.java:99)
    E/AndroidRuntime(18317): 	at android.os.Looper.loop(Looper.java:223)
    E/AndroidRuntime(18317): 	at android.os.HandlerThread.run(HandlerThread.java:67)
    I/Process (18317): Sending signal. PID: 18317 SIG: 9
    

how can I fix it?

my code looks like:

      @override
      Widget build(BuildContext context) {
        return MapWidget(
          key: const ValueKey("mapWidget_Event_Location"),
          cameraOptions: CameraOptions(
            center: Point(
              coordinates: Position(-10.173944601588289, 39.74879879604326),
            ).toJson(),
            zoom: 12,
          ),
          styleUri: mapBoxStyle,
          onMapCreated: _onMapCreated,
          onTapListener: _onTap,
          onScrollListener: _onScrollListener,
          onMapIdleListener: _onMapIdle,
        );
      }

**Comment by ember11498** [comment]
I tried many other emulators and couldnt make it work. I always get the same error. Seems my emulators dont support OpenGL ES 3.0 context? What should I do?

**Comment by baleboy** [comment]
This seems to be an issue with your emulator config rather than Mapbox. Can you share more details about what emulator you use and on what platform?

**Comment by ember11498** [comment]
@baleboy thank you for your reply. Following I'll show you several pictures of my emulator:

Note:my computer is omen 15, windows.

![image](https://github.com/mapbox/mapbox-maps-flutter/assets/135765222/60a7c2de-12b2-4cd4-b785-2d8c7f4b6471)

![image](https://github.com/mapbox/mapbox-maps-flutter/assets/135765222/7ef79e8f-499b-459d-9716-4f86761c40d9)

![image](https://github.com/mapbox/mapbox-maps-flutter/assets/135765222/a16919f4-f82b-49d6-9d46-7cd877e1b84d)

![image](https://github.com/mapbox/mapbox-maps-flutter/assets/135765222/1ae205ea-eced-4a2d-87c5-558ef01facca)

![image](https://github.com/mapbox/mapbox-maps-flutter/assets/135765222/d17cf066-d8a0-4840-b93b-94234a9ca7cf)

![image](https://github.com/mapbox/mapbox-maps-flutter/assets/135765222/b161e03c-9a1a-40e1-9167-982191a8d4bd)

![image](https://github.com/mapbox/mapbox-maps-flutter/assets/135765222/916b0f10-a618-4d8d-9eed-9d6a0ffd1fda)

![image](https://github.com/mapbox/mapbox-maps-flutter/assets/135765222/454382ef-d74c-40d8-b193-32378208f7b3)

![image](https://github.com/mapbox/mapbox-maps-flutter/assets/135765222/582802fe-457a-4b2b-8e12-313a3cb14956)

![image](https://github.com/mapbox/mapbox-maps-flutter/assets/135765222/e05e529f-99cf-45a6-8699-656c792910f6)

![image](https://github.com/mapbox/mapbox-maps-flutter/assets/135765222/8b597acf-b0b6-4623-b4e3-8d929b7ee69c)

![image](https://github.com/mapbox/mapbox-maps-flutter/assets/135765222/46304f45-b622-4a93-8f61-299e90fe4981)

![image](https://github.com/mapbox/mapbox-maps-flutter/assets/135765222/98ea3f2f-6dd9-4939-b266-81ab7e999df2)

![image](https://github.com/mapbox/mapbox-maps-flutter/assets/135765222/cde0a382-3126-4fc0-9d7a-290cfb052df4)

**Comment by ember11498** [comment]
@baleboy just one more thing. I remember when I went to location in my emulator a map would show up. This was months ago. But now it seems it doesn't even render the map and it's all blank if you see the picture I sent you in the location setting on the emulator

**Comment by ember11498** [comment]
@baleboy I will try this solution when I arrieve home (in 8 hours).

https://stackoverflow.com/questions/77612277/android-emulator-location-map-is-not-loading

Basically they say "it can be resolved by updating the Android SDK Platform-Tools and Android Emulator."

**Comment by ember11498** [comment]
@baleboy you can close. issue is fixed after i updated android SDK tools

**Comment by baleboy** [comment]
Great, thanks for the follow-up!

**Comment by angry010101** [comment]
Hello, Can you please add some checks to the code so that the app doesn't crash when this error occurs?
