### ISSUE TITLE
how to support privacy manifest in mapbox_maps_flutter 0.5.0

### ISSUE THREAD

**Issue by dea-hayashida-yoshiki** [mapbox/mapbox-maps-flutter#506]
I am currently using version 0.5.0 of the mapbox_maps_flutter package.
I have read issue #475 on GitHub and understand that version 1.1.0 will include support for the Privacy Manifest.
However, the cost of updating to the newer version is quite high for me.
Is there any way I can remain on version 0.5.0 and still address the Privacy Manifest requirements, perhaps through a patch or other method?

**Comment by maios** [comment]
Hi @dea-hayashida-yoshiki, thank you for raising this issue, we have published new version [0.6.0](https://pub.dev/packages/mapbox_maps_flutter/versions/0.6.0/install) that included fix for Privacy Manifest, please try it out and let us know if it helps :)

**Comment by dea-hayashida-yoshiki** [comment]
Thank you so much for the quick response and the new version 0.6.0 with the fix for the Privacy Manifest issue.
I really appreciate your team's prompt action and attention to this matter.
