### ISSUE TITLE
1.1.0 version solving failed

### ISSUE THREAD

**Issue by M2dL1fe** [mapbox/mapbox-maps-flutter#508]
Because xxxxx depends on mapbox_maps_flutter ^1.1.0 which doesn't match any versions, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on mapbox_maps_flutter: flutter pub add mapbox_maps_flutter:^1.0.0

**Comment by evil159** [comment]
Hi @M2dL1fe, have you tried running `flutter pub get`?

**Comment by M2dL1fe** [comment]
Yes, still @evil159

**Comment by M2dL1fe** [comment]
Suddenly ok
