### ISSUE TITLE
Turn the map according to the direction

### ISSUE THREAD

**Issue by senaMyunghee** [mapbox/mapbox-maps-flutter#509]
How can I use TRACKING_COMPASS mode ? ( supported by mapbox_gl )

**Comment by basvdijk** [comment]
This issue should help you https://github.com/mapbox/mapbox-maps-flutter/issues/33 with fixing this. Basicually what you do is set the bearing to the correct compass direction.

**Comment by senaMyunghee** [comment]
thanks @basvdijk 
but i want stream listener not a periodic.
I need more smooth movement

**Comment by basvdijk** [comment]
I have achieved smooth rotating and moving with this solution. I agree it is not the nicest solution. We have to wait till the development team implemented the viewport api. Unfortunately there is no timeline for this. See the comment of https://github.com/mapbox/mapbox-maps-flutter/issues/33#issuecomment-2070135742

**Comment by senaMyunghee** [comment]
I see. thank you :)
