### ISSUE TITLE
Android: launch issue with newly exposed attribution in 0.4.0

### ISSUE THREAD

**Issue by widike** [mapbox/mapbox-maps-flutter#52]
Now I get this trying to launch on Android:

`/android/src/main/kotlin/com/mapbox/maps/mapbox_maps/mapping/LogoMappings.kt: (8, 1):
Conflicting overloads: public fun AttributionSettingsInterface.applyFromFLT(settings: FLTSettings.AttributionSettings, context: Context):
Unit defined in com.mapbox.maps.mapbox_maps.mapping in file AttributionMappings.kt, public fun LogoSettingsInterface.applyFromFLT(settings: FLTSettings.LogoSettings, context: Context):
Unit defined in com.mapbox.maps.mapbox_maps.mapping in file LogoMappings.kt, public fun AttributionSettingsInterface.applyFromFLT(settings: FLTSettings.AttributionSettings, context: Context):
Unit defined in com.mapbox.maps.mapbox_maps.mapping in file AttributionMappings.kt, public fun LogoSettingsInterface.applyFromFLT(settings: FLTSettings.LogoSettings, context: Context):
Unit defined in com.mapbox.maps.mapbox_maps.mapping in file LogoMappings.kt`

**Comment by geisterfurz007** [comment]
Try running `flutter clean`, then relaunch your project.
