### ISSUE TITLE
Mapbox Pop Up

### ISSUE THREAD

**Issue by sukianto** [mapbox/mapbox-maps-flutter#529]
Hi, I have search all the functions from the sample but cannot find the pop up function that is the same with mapboxgl.js:
[https://docs.mapbox.com/mapbox-gl-js/example/popup/](https://docs.mapbox.com/mapbox-gl-js/example/popup/)

Anyone is the popup function is there, or maybe there is similar function on mapbox-maps-flutter?

Thank you.

**Comment by AlbertoNoris** [comment]
It's currently not available in this package.

**Comment by sukianto** [comment]
I see, understood then. Thank you.

**Comment by brandonwatkins** [comment]
Any updates on when this feature will be available? or if its on the roadmap at all?
