### ISSUE TITLE
How to add a nice looking marker to the map?

### ISSUE THREAD

**Issue by dawid-niedzwiecki** [mapbox/mapbox-maps-flutter#55]
Can i somehow make a nice looking circle marker with a text on top of it directly in the map without giving it an image?

**Comment by kamami** [comment]
You could make use of layers. There are a bunch of different ones

**Comment by dawid-niedzwiecki** [comment]
Is there a structure that I would need to follow? How do I add some vector graphics to the mapp in code?

**Comment by dawid-niedzwiecki** [comment]
I'm thinking of something that looks like this:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/19879399/214244547-1c7a568e-7b85-423c-9213-72d486b4f67e.png">

Is it possible without having any image file at hand? Can I draw such markers as single features using some shapes and stuff?

**Comment by kamami** [comment]
You could use two separate layers. One for the circles and the other for the text. Just like in the cluster example.
