### ISSUE TITLE
[ iOS ] How to remove or hide the lat-lon-zoom-bearing info window ?

### ISSUE THREAD

**Issue by yfming93** [mapbox/mapbox-maps-flutter#552]
How to remove or hide the lat-lon-zoom-bearing info window ? Android has work well not show it. It was showing on iOS at topletf in all page .
<img width="420" alt="image" src="https://github.com/mapbox/mapbox-maps-flutter/assets/18211498/216178b0-2bd4-49b7-8283-03e92c018456">

**Comment by evil159** [comment]
Hi @yfming93, thanks for raising this, it seems that a debug flag made its way into 2.0.0-rc.1 release, it will be removed in the 2.0.0.

**Comment by yfming93** [comment]
> Hi @yfming93, thanks for raising this, it seems that a debug flag made its way into 2.0.0-rc.1 release, it will be removed in the 2.0.0.

Thank you. I Got it.

**Comment by evil159** [comment]
Fixed in v2.0.0
