### ISSUE TITLE
onMapCreated is called when app is switching to background

### ISSUE THREAD

**Issue by kamami** [mapbox/mapbox-maps-flutter#57]
When putting the application in the background and switch to another app, onMapCreated is called. Indeed it is called twice...

```
  _onMapCreated(MapboxMap mapboxMap) async {
    print("onMapCreated");
}
```

**EDIT:**

```
import 'package:flutter/material.dart';
import 'package:mapbox_maps_flutter/mapbox_maps_flutter.dart';

void main() async {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MapView(),
    );
  }
}

class MapView extends StatefulWidget {
  const MapView({super.key});

  @override
  State<MapView> createState() => _MapViewState();
}

class _MapViewState extends State<MapView> {
  
  _onMapCreated(MapboxMap mapboxMap) async {
    print("onMapCreated");
  }

  @override
  Widget build(BuildContext context) {
    return MapWidget(
      cameraOptions: CameraOptions(
          padding: MbxEdgeInsets(
              bottom: (MediaQuery.of(context).size.height -
                      kBottomNavigationBarHeight -
                      MediaQuery.of(context).padding.top) *
                  0.15,
              left: 0,
              right: 0,
              top: 0),
          zoom: 4,
          center: {
            "coordinates": [9.142084916929944, 49.97744579860142]
          }),
      resourceOptions: ResourceOptions(
          accessToken:
              "XXX"),
      onMapCreated: _onMapCreated,
    );
  }
}
```

**Comment by kamami** [comment]
@LjubiTech-Maxko I edited the initial issue. 
Seems to be related to the CameraOptions imo.

**Comment by LjubiTech-Maxko** [comment]
Please edit the sample code and delete your accessToken.

**Comment by kamami** [comment]
> Please edit the sample code and delete your accessToken.

Yes, just saw it. Thanks

**Comment by LjubiTech-Maxko** [comment]
This is probably related to the #26. Every time build is called (regardless of the `MediaQuery` usage in the `CameraOptions`) on the widget which contains the `MapWidget`, `onMapCreated` is called which can be seen in the following source code from repo.

https://github.com/mapbox/mapbox-maps-flutter/blob/308d25dac22f2402a79292cd6fa5a37f2973643b/lib/src/map_widget.dart#L177-L195

Considering this and the fact that @yunikkk already assigned himself on the mentioned issue, we can only wait for it to be resolved internally.

**Comment by kamami** [comment]
Oh no...
Hopefully they already came up with a fix for this issues.
These lifecycle bugs are the worst kind and could really be a dealbreaker.
@yunikkk Do you already have a solution coming up for this?

**Comment by kamami** [comment]
Any statement or forecast for this?

**Comment by LjubiTech-Maxko** [comment]
As a workaround until this is resolved, you could fork the repo and delete the lines 189-191 in the previous comment considering there is already `onMapCreated` callback in `onPlatformViewCreated`. This could be the real solution because it should be called, as its name states, only when map is created, and that is done from `onPlatformViewCreated` callback which is called only once.

**Comment by kamami** [comment]
Very nice, thanks a lot!

**Comment by Strafe0** [comment]
Try to add key

**Comment by kamami** [comment]
@Strafe0 Does not work.
I already have a key `key: const ValueKey("mapWidget")` assigned to the widget.

**Comment by markpeterfejes** [comment]
> As a workaround until this is resolved, you could fork the repo and delete the lines 189-191 in the previous comment considering there is already `onMapCreated` callback in `onPlatformViewCreated`. This could be the real solution because it should be called, as its name states, only when map is created, and that is done from `onPlatformViewCreated` callback which is called only once.

Shall we make a pull request for this change? As far as I understand this is also blocking being able to assign the map to a `final late` variable.

**Comment by LjubiTech-Maxko** [comment]
@kamami Just a note, I think your solution to update the camera padding in the build method won't work because those parameters are only used when the map is created and are not updated later although they have been changed.

@markpeterfejes I thought about opening a pull request but when doing some tests to check if there is a reason for `mapCreated` being called inside build method, I found the mentioned bug of not updating changed parameters when `MapWidget` is rebuilt, and decided try to find a solution to that and open a pull request with both changes. But as far as I am concerned you can open the pull request with only those 2 lines of code deleted.

**Comment by kamami** [comment]
> @kamami Just a note, I think your solution to update the camera padding in the build method won't work because those parameters are only used when the map is created and are not updated later although they have been changed.
> 
> @markpeterfejes I thought about opening a pull request but when doing some tests to check if there is a reason for `mapCreated` being called inside build method, I found the mentioned bug of not updating changed parameters when `MapWidget` is rebuilt, and decided try to find a solution to that and open a pull request with both changes. But as far as I am concerned you can open the pull request with only those 2 lines of code deleted.

Yes I am aware of that'd removed the padding again. I just moved the whole widget up in my stack now.
