### ISSUE TITLE
[ask] Is there a way to hide some of the pins that are visible in Mapbox?

### ISSUE THREAD

**Issue by iseruuuuu** [mapbox/mapbox-maps-flutter#587]
# Description
I would like to be able to remove some of the pins (e.g., schools, parks, etc.) that are initially displayed when the Mapbox map is displayed.

My apologies if this is mentioned in the documentation or elsewhere.

# enviroment

```
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.4.1 23E224 darwin-arm64 (Rosetta), locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.90.0)

```

```pubspec.yaml
dependencies: 
  mapbox_maps_flutter: ^2.0.0

```

# UI

<img src="https://github.com/mapbox/mapbox-maps-flutter/assets/67954894/2829fa35-2c3e-43a9-8ac6-ba427cf741a8" width="200"/>

**Comment by evil159** [comment]
Hi @iseruuuuu, if you are using the Standard style you can configure visibility of road/place/POI/transit labels through the style configuration API https://docs.mapbox.com/mapbox-gl-js/guides/styles/#mapbox-standard-1. Alternatively, all the configurations are also available in the [Mapbox Studio](https://docs.mapbox.com/studio-manual/guides/map-styling/#the-style-editor).

Closing this issue, feel free to reopen if you have more questions.

**Comment by iseruuuuu** [comment]
@evil159 
Thanks. After I post this issues and I find how to fix it.
