### ISSUE TITLE
FillLayerExpression not working in v2.1.0-beta.1

### ISSUE THREAD

**Issue by Kishore2407** [mapbox/mapbox-maps-flutter#588]
I need to change the tapped feature layer color using its feature state id.. So i used fillLayerExpression with boolean expression .. but its not working.

```
await mapboxMap?.style.addLayer(
  FillLayer(
    id: 'pond_boundary_tile1_fill',
    sourceId: 'pond_boundary_tile1_source',
    sourceLayer: 'aquasat-tile1',
    fillColorExpression: [
      'case',
      ['boolean', ['feature-state', 'selected'], false],
      "#004fbb",
      "#dbdbdb",
    ],
  ),
);
```

this is my ontaplistener code 

```
Future<void> onTapListener(MapContentGestureContext context, Function setState) async {
  final touchPosition = context.touchPosition;
  print("Coordinates: (${touchPosition.x}, ${touchPosition.y})");

  final List<QueriedRenderedFeature?> features =
      await mapboxMap!.queryRenderedFeatures(
    RenderedQueryGeometry(
      value: jsonEncode(touchPosition.encode()),
      type: Type.SCREEN_COORDINATE,
    ),
    RenderedQueryOptions(
        layerIds: ['pond_boundary_tile1_fill'], filter: null),
  );

  if (features.isNotEmpty) {
    final QueriedFeature selectedFeature = features.first!.queriedFeature;
    featureId = selectedFeature.feature['id'].toString();
    print("Tapped feature ID: $featureId");
    appController.setFeatureId = featureId;

    print("Current selectedFeatureId: $selectedFeatureId");
    print("Current featureId: $featureId");

    if (selectedFeatureId != null && selectedFeatureId != featureId) {
      await mapboxMap?.setFeatureState(
        'pond_boundary_tile1_source',
       'pond_boundary_tile1_fill',
        selectedFeatureId!,
        jsonEncode({'selected': false}),
      );
    }

    await mapboxMap?.setFeatureState(
      'pond_boundary_tile1_source',
      'pond_boundary_tile1_fill',
      featureId!,
      jsonEncode({'selected': true}),
    );

 
    setState(() {
      selectedFeatureId = featureId;
    });

    final featureState = await mapboxMap?.getFeatureState(
      'pond_boundary_tile1_source',
      'pond_boundary_tile1_fill',
      featureId!,
    );
    print("Feature state for ID $featureId: $featureState");

    print("Feature ID: $featureId, selectedFeatureId: $selectedFeatureId");

}
}
```

**Comment by ViswanthSanthosh** [comment]
I am also facing same problem.. Please help

**Comment by Dinesh071993** [comment]
I am also facing same problem.. Please Resolve ASAP

**Comment by GangaJeganathan** [comment]
I am also facing same problem.. Please Resolve ASAP

**Comment by evil159** [comment]
Hi @Kishore2407, thank you for your report! I see incorrect `sourceLayerId` argument in `setFeatureState(...)` method, in your case it should be `aquasat-tile1`, if I understand your setup correctly.
```dart
      await mapboxMap?.setFeatureState(
        'pond_boundary_tile1_source',
       'aquasat-tile1',
        selectedFeatureId!,
        jsonEncode({'selected': false}),
      );
```

I don't know the layout of your source, but in my tests with a simple geo json with a single layer your code works just fine if I specify the correct source layer.

**Comment by Kishore2407** [comment]
Hai @evil159 can i able to use layer.properties.id instead of feature id??

**Comment by sergannn** [comment]
@Kishore2407     final feature = features!.first;
      print("tapped ${feature}");

      print(feature?.queriedFeature.state);
      print(feature?.queriedFeature.sourceLayer);
      print('..${feature!.queriedFeature.feature}');
      // Access properties safely
      final propertiesStr =
          feature.queriedFeature.feature['properties'].toString();
      String jsonStr = propertiesStr
          .replaceAll('{', '{"')
          .replaceAll(': ', '": "')
          .replaceAll(', ', '", "')
          .replaceAll('}', '"}');
      var name;
      var id;
      try {
        Map<String, dynamic> properties = jsonDecode(jsonStr);
        name = properties['name'];
        id = properties['id'];
        print('ID: $id, Name: $name'); i made hard code like that
