### ISSUE TITLE
Xcode16 beta 

### ISSUE THREAD

**Issue by chenjie1219** [mapbox/mapbox-maps-flutter#592]
MapboxMaps/Sources/MapboxMaps/Annotations/ViewAnnotationManager.swift:84:19 Cannot convert return expression of type '[UIView : ViewAnnotationOptions]' to return type 'Dictionary<String, Optional<JSONValue>>.RawValue' (aka 'Dictionary<String, Optional<Any>>')

![image](https://github.com/mapbox/mapbox-maps-flutter/assets/16828878/ea2d63ce-59be-4205-9af2-25cb0b330bf6)

**Comment by fodedoumbouya** [comment]
+1

**Comment by fodedoumbouya** [comment]
@maios

**Comment by maios** [comment]
@chenjie1219 which MapboxMaps Flutter are you using?

**Comment by chenjie1219** [comment]
> @chenjie1219您正在使用哪个 MapboxMaps Flutter？

mapbox_maps_flutter: ^2.0.0

**Comment by maios** [comment]
could you try with [2.1.0-beta.1](https://pub.dev/packages/mapbox_maps_flutter/versions/2.1.0-beta.1)? We have made changes to make iOS SDK adaptable to Xcode 16 in [MapboxMaps iOS v11.5.0-beta.1](https://github.com/mapbox/mapbox-maps-ios/releases/tag/v11.5.0-beta.1), and it should be already integrated to our Flutter 2.1.0-beta.1

**Comment by fodedoumbouya** [comment]
thank you @maios
