### ISSUE TITLE
LineString.fromPoints not existing in 2.1.0-beta1 anymore

### ISSUE THREAD

**Issue by basvdijk** [mapbox/mapbox-maps-flutter#594]
```
        Feature<LineString> featureLineString = Feature<LineString>(
          geometry: LineString.fromPoints(points: [previousPoint, point]),
        );
```

It turns out that now ` LineString.fromJson` is the only one available. How should the code above be changed to work again? Or is `fromPoints` accidentally removed?

**Comment by basvdijk** [comment]
I have fixed this by importing turf and use `turf.LineString` I leave this issue open till someone confirmed that this is desired way to do this.

**Comment by evil159** [comment]
@basvdijk Good catch, I added them back in #596. Meanwhile, you can also use this constructor out-of-box: `LineString(coordinates: [point.coordinates])`.

**Comment by evil159** [comment]
`LineString.fromPoints` should be there in 2.1.0-rc.1.
