### ISSUE TITLE
MapWidget not closing properly.

### ISSUE THREAD

**Issue by sauravniraula** [mapbox/mapbox-maps-flutter#595]
https://github.com/mapbox/mapbox-maps-flutter/assets/52109383/9a9bca4a-b723-4fe7-a3d1-1f74272b5d18

When popping from page with map widget, map gets stuck and shows weird overlay.

**Comment by hussenIbrahim** [comment]
in MapWidget
androidHostingMode : AndroidPlatformViewHostingMode.TLHC_HC
