### ISSUE TITLE
PlatformException(error, java.lang.IllegalStateException: Please ensure that the hosting activity/fragment is a valid LifecycleOwner

### ISSUE THREAD

**Issue by alexeileyvamora** [mapbox/mapbox-maps-flutter#60]
E/flutter ( 6746): 	at com.mapbox.maps.plugin.lifecycle.ViewLifecycleOwner.doOnAttached(ViewLifecycleOwner.kt:68)
E/flutter ( 6746): 	at com.mapbox.maps.plugin.lifecycle.ViewLifecycleOwner.<init>(ViewLifecycleOwner.kt:58)
E/flutter ( 6746): 	at com.mapbox.maps.plugin.lifecycle.MapboxLifecyclePluginImpl.registerLifecycleObserver(MapboxLifecyclePluginImpl.kt:30)
E/flutter ( 6746): 	at com.mapbox.maps.plugin.MapPluginRegistry.onAttachedToWindow(MapPluginRegistry.kt:173)
E/flutter ( 6746): 	at com.mapbox.maps.MapController.onAttachedToWindow$sdk_release(MapController.kt:333)
E/flutter ( 6746): 	at com.mapbox.maps.MapView.onAttachedToWindow(MapView.kt:115)
E/flutter ( 6746): 	at android.view.View.dispatchAttachedToWindow(View.java:19702)
E/flutter ( 6746): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3518)
E/flutter ( 6746): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3525)
E/flutter ( 6746): 	at android.view.ViewGroup.addViewInner(ViewGroup.java:5255)
E/flutter ( 6746): 	at android.view.ViewGroup.addView(ViewGroup.java:5035)
E/flutter ( 6746): 	at android.view.ViewGroup.addView(ViewGroup.java:4972)
E/flutter ( 6746): 	at android.view.ViewGroup.addView(ViewGroup.java:4945)
E/flutter ( 6746): 	at io.flutter.plugin.platform.PlatformViewsController$1.configureForTextureLayerComposition(PlatformViewsController.java:647)
E/flutter ( 6746): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:225)
E/flutter ( 6746): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:128)
E/flutter ( 6746): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/flutter ( 6746): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/flutter ( 6746): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter ( 6746): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter ( 6746): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 6746): 	at android.os.Handler.handleCallback(Handler.java:914)
E/flutter ( 6746): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/flutter ( 6746): 	at android.os.Looper.loop(Looper.java:225)
E/flutter ( 6746): 	at android.app.ActivityThread.main(ActivityThread.java:7563)
E/flutter ( 6746): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 6746): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/flutter ( 6746): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)

**Comment by yunikkk** [comment]
Hey @alexeileyvamora , any details about your setup? Have you tried the sample application, does it work on your device?

**Comment by alexeileyvamora** [comment]
@yunikkk Thanks for answering me. I am using the flutter_mapbox_navigation package
I have fixed it at the moment with 

configurations 
{
  all*.exclude group: 'com.mapbox.plugin', module: 'maps-lifecycle'
} 

from android\app\buid.gradle

**Comment by evil159** [comment]
Hi all, this issue should be fixed in https://github.com/mapbox/mapbox-maps-flutter/pull/478, feel free to reopen this ticket if you have any feedback!
