### ISSUE TITLE
3D file asset (gbl) is not working

### ISSUE THREAD

**Issue by NaimAbb** [mapbox/mapbox-maps-flutter#659]
I have a problem, which is that the 3D file does not appear on the map (from assets)

<img width="866" alt="Screenshot 2024-08-20 at 12 15 24 AM" src="https://github.com/user-attachments/assets/2f952c6f-4f2c-4a6b-9bc3-7d661f3bf354">
<img width="805" alt="Screenshot 2024-08-20 at 12 15 40 AM" src="https://github.com/user-attachments/assets/404f53b4-dc8a-4671-9f2f-5439a336aba3">

**Comment by maios** [comment]
Hi @NaimAbb , unfortunately local asset is not working with `addStyleModel` API yet, only for `LocationPuck3D` and `ModelLayer`. So in your example, you can remove the code where you addStyleModel, and just specify the local path in `ModelLayer/modelId`

```
modelLayer1.modelId = "asset://assets/sportcar.glb:
```

**Comment by NaimAbb** [comment]
> Hi @NaimAbb , unfortunately local asset is not working with `addStyleModel` API yet, only for `LocationPuck3D` and `ModelLayer`. So in your example, you can remove the code where you addStyleModel, and just specify the local path in `ModelLayer/modelId`
> 
> ```
> modelLayer1.modelId = "asset://assets/sportcar.glb:
> ```



> Hi @NaimAbb , unfortunately local asset is not working with `addStyleModel` API yet, only for `LocationPuck3D` and `ModelLayer`. So in your example, you can remove the code where you addStyleModel, and just specify the local path in `ModelLayer/modelId`
> 
> ```
> modelLayer1.modelId = "asset://assets/sportcar.glb:
> ```



> Hi @NaimAbb , unfortunately local asset is not working with `addStyleModel` API yet, only for `LocationPuck3D` and `ModelLayer`. So in your example, you can remove the code where you addStyleModel, and just specify the local path in `ModelLayer/modelId`
> 
> ```
> modelLayer1.modelId = "asset://assets/sportcar.glb:
> ```

Thank you it's working now

**Comment by NaimAbb** [comment]
> Hi @NaimAbb , unfortunately local asset is not working with `addStyleModel` API yet, only for `LocationPuck3D` and `ModelLayer`. So in your example, you can remove the code where you addStyleModel, and just specify the local path in `ModelLayer/modelId`
> 
> ```
> modelLayer1.modelId = "asset://assets/sportcar.glb:
> ```

Thank you it's working now

**Comment by NaimAbb** [comment]
> Hi @NaimAbb , unfortunately local asset is not working with `addStyleModel` API yet, only for `LocationPuck3D` and `ModelLayer`. So in your example, you can remove the code where you addStyleModel, and just specify the local path in `ModelLayer/modelId`
> 
> ```
> modelLayer1.modelId = "asset://assets/sportcar.glb:
> ```

Thank you it is working now
