### ISSUE TITLE
Listener for tap on map but not on marker

### ISSUE THREAD

**Issue by BenKfm** [mapbox/mapbox-maps-flutter#66]
Hey there, 
as there is no listener for a tap on the map (but not on a marker), how do we do that?
Is there an ordering to the call sequence of listeners? Like, is the onTapListener always called before the onPointAnnotationClick listener? Can we rely on that? 

Also: i need to be able to cluster (so i will have to go with a GeoJson source), but how does a onTap work then (i dont have PointAnnotations anymore, so no onPointAnnotationClickListener)... do i have to map the coordinates from onTapListener to a entity from my GeoJson source?

Cheers and thanks!

**Comment by AIT-anhlt** [comment]
I don't know my answer is good for you or not. 
Actually, MapWidget has onMapTapListener prop. You need to implement it.
From the ScreenCoordinate, you can find all features on the Map that you already Tapped.

**Comment by LjubiTech-Maxko** [comment]
You can achieve that with the following code. This queries for rendered features where user clicked.

```dart
// Callback for MapWidget onTapListener
Future<void> onTapListener(ScreenCoordinate coord) async {
    // need to convert coord to real ScreenCoordinate for querying features.
    final ScreenCoordinate conv = await _mapboxMap!.pixelForCoordinate(
      Point(
        coordinates: Position(
          coord.y, coord.x,
        ),
      ).toJson(),
    );

    final List<QueriedFeature?> features = await _mapboxMap!.queryRenderedFeatures(
      RenderedQueryGeometry(
        value: jsonEncode(conv.encode()),
        type: Type.SCREEN_COORDINATE,
      ),
      // add these options if you want to query only specific layer,
      // for example, your layer which is using mentioned gejson source
      RenderedQueryOptions(
        layerIds: ['layer_id_1', 'layer_id_2', ...],
      ),
    );
    
    // do what you need with the features
}
```

**Comment by BenKfm** [comment]
Thanks, that works just fine!
