### ISSUE TITLE
SymbolLayer and FillLayer not showing with VectorTiles Style

### ISSUE THREAD

**Issue by RAglx** [mapbox/mapbox-maps-flutter#674]
Dear Mapbox Flutter team,

if I set a vectortile layer with `setStyleURI` there are geometries missing in the map.

See the attached file with included geojson. 
[style.zip](https://github.com/user-attachments/files/16844720/style.zip)
It's the _style.dart_ file from your example project. Just copy it to _\example\lib_ and run the app. 
Choose _Style interface_ and then switch through the styles by hitting the _setStyleURI_ button.

You can see, that the polygons are rendered correctly with your Mapbox default styles.
But they do disappear with the vectortiles.
If you comment out the `topicsLabels` layer, everything works as expected.

I tried several options for the `SymbolLayer`, like `textIgnorePlacement` or `textAllowOverlap` but without effect.

Am I doing something wrong? Is there an option which I'm missing? Or is it a bug?

Greets and thanks

| ![Mapbox 1](https://github.com/user-attachments/assets/dfee1fc5-e488-47eb-a394-9b36629f637e) | ![Mapbox 2](https://github.com/user-attachments/assets/7a636b13-c64e-42c5-b066-193067229ba0) | ![Vectortiles 1](https://github.com/user-attachments/assets/e3b7d2ea-47df-4e77-91a5-462a0c617971) | ![Vectortiles 2](https://github.com/user-attachments/assets/2355b544-a5a9-4939-ad18-5e57f880890e) |
|---|---|---|---|

**Comment by endanke** [comment]
@RAglx we looked at the example you provided, and it looks like that the issue is with the specification of the font. Because your style uses a custom glyph configuration, you need to specify the font in your custom symbol layers.
We tried to set it to `Frutiger Neue Regular` which you use in your style and that fixes the rendering of the custom layers.

**Comment by RAglx** [comment]
Yes indeed! 🥳 Setting the font to `Frutiger Neue Regular` after setting the style to vectortiles solves the problem completely.
Thank you very much for your answer.


PS: Interestingly this also fixes an issue I had with other polygons when vectortiles were displayed:
| Before setting the font (somehow correupted) | Font set to Frutiger for vectortiles (solved) |
| --- | --- |
| ![Before setting the font](https://github.com/user-attachments/assets/bd44eed9-41bd-46df-a3ee-9e7d808facc6) | ![Font set to Frutiger](https://github.com/user-attachments/assets/26bdfcb6-6c73-42a3-a308-38a5be7c871c) |
