### ISSUE TITLE
This package is stopping app from compiling in android after upgrading flutter to 3.24.1, ios works fine

### ISSUE THREAD

**Issue by jatin-web** [mapbox/mapbox-maps-flutter#684]
After I upgraded the flutter version to 3.24.1, this package is stopping app from compiling in android, iOS still works fine.

Error:
<img width="1386" alt="Screenshot 2024-09-13 at 11 36 06 AM" src="https://github.com/user-attachments/assets/e17a91fd-c8a1-4432-be2c-2389cf93f645">

"flutter doctor -v"  output
<img width="1034" alt="Screenshot 2024-09-13 at 11 35 24 AM" src="https://github.com/user-attachments/assets/74d8989e-1f8e-4c1c-a873-c25e8bd03049">

How should I proceed to fix this error?

**Comment by baleboy** [comment]
What version of the plugin do you use? We recently [fixed an issue](https://github.com/mapbox/mapbox-maps-flutter/pull/668) for Flutter 3.24.1, published in release 2.2.1. I can't tell from the logs if it's the same issue though.

**Comment by jatin-web** [comment]
> What version of the plugin do you use? We recently [fixed an issue](https://github.com/mapbox/mapbox-maps-flutter/pull/668) for Flutter 3.24.1, published in release 2.2.1. I can't tell from the logs if it's the same issue though.

I am using mapbox_maps_flutter: ^2.2.1

**Comment by baleboy** [comment]
Did you try a clean build by running `flutter clean` and `flutter pub get`? If you did and it didn't help, then we would need to know more details about the project.

**Comment by ciakov** [comment]
I had the same problem with mapbox_maps_flutter: 2.2.1, and flutter version 3.24.3.
I have tried everything that you mentioned flutter clean - flutter pub get
I even tried downgrading flutter to version 3.24.1 but it didn't helped.
The solution was to upgrade gradle to 8.4, 
at [Project]/android/gradle/wrapper/gradle-wrapper.properties I set
distributionUrl=https\://services.gradle.org/distributions/gradle-8.4-all.zip
After this everything worked fine.

**Comment by baleboy** [comment]
thanks for sharing the resolution!

**Comment by VuThienHung** [comment]
Hi everyone

I am using flutter 3.24.3 and XCode 15.3
mapbox_maps_flutter: 2.3.0

And i have an issue like photo

Could you help me?

Thanks
![Screenshot 2024-10-16 at 15 42 31](https://github.com/user-attachments/assets/81b63bcb-3eea-4700-be42-8669a06fce31)
