### ISSUE TITLE
The first debug failed 

### ISSUE THREAD

**Issue by usenameI** [mapbox/mapbox-maps-flutter#694]
Error while receiving file changes
net.rubygrapefruit.platform.NativeException: Error received when handling events, error = 87: C:\dev\flutter\packages\flutter_tools\gradle
        at net.rubygrapefruit.platform.internal.jni.AbstractNativeFileEventFunctions$NativeFileWatcher.executeRunLoop0(Native Method)
        at net.rubygrapefruit.platform.internal.jni.AbstractNativeFileEventFunctions$NativeFileWatcher.executeRunLoop(AbstractNativeFileEventFunctions.java:42)
        at net.rubygrapefruit.platform.internal.jni.AbstractFileEventFunctions$AbstractFileWatcher$1.run(AbstractFileEventFunctions.java:154)
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
ERROR:C:\Users\Administrator\.gradle\caches\transforms-4\4018a4ad7aa6c3acfe5ac46d628068af\transformed\lifecycle-livedata-core-2.8.4-runtime.jar: D8: java.lang.NullPointerException

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform lifecycle-livedata-core-2.8.4.aar (androidx.lifecycle:lifecycle-livedata-core:2.8.4) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: C:\Users\Administrator\.gradle\caches\transforms-4\4018a4ad7aa6c3acfe5ac46d628068af\transformed\lifecycle-livedata-core-2.8.4-runtime.jar.
         > Error while dexing.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

**Comment by deandreamatias-worldline** [comment]
@usenameI how solve this?
