### ISSUE TITLE
Draw Tools for mapbox-maps-flutter

### ISSUE THREAD

**Issue by felixerdy** [mapbox/mapbox-maps-flutter#703]
Is there something like https://github.com/mapbox/mapbox-gl-draw in mapbox-maps-flutter? 

I want my users to create polygons on a map

**Comment by m-hamza-tanbits** [comment]
https://pub.dev/packages/mapbox_draw_polygon_area
for draw polygon and polyline you can use this package.

**Comment by felixerdy** [comment]
> https://pub.dev/packages/mapbox_draw_polygon_area for draw polygon and polyline you can use this package.

This package uses a different mapbox package (https://pub.dev/packages/mapbox_gl_modified) in their example, I'm not sure if I can use it with mapbox-maps-flutter

**Comment by felixerdy** [comment]
I wasn't able to find a solution for my needs, so I created my own draw tools: https://github.com/felixerdy/mapbox-maps-flutter-draw
