### ISSUE TITLE
Uable to load local 3d models from assets.

### ISSUE THREAD

**Issue by nforesperance** [mapbox/mapbox-maps-flutter#736]
I have been trying to load local models from my assets and nothing gets displayed.
From what I know, the issue was fixed in the [v2.2.0 Release](https://github.com/mapbox/mapbox-maps-flutter/releases/tag/2.2.0)
But I am currently using the ^2.3.0 and nothing gets displayed. I even downgraded to v2.2.0 and it still does not appear.
Even the example project for loading models, given in  [model_layer_example.dart](https://github.com/mapbox/mapbox-maps-flutter/blob/main/example/lib/model_layer_example.dart) from the example project only displays the remote model.
Thanks

**Comment by maios** [comment]
Hi, it was a mistake in our example, `addStyleModel` does not support local asset path yet, instead, you can provide the asset path directly to `ModelLayer/modelId` as shown below
```
var modelLayer1 = ModelLayer(id: "modelLayer-car", sourceId: "sourceId");
modelLayer1.modelId = "asset://assets/sportcar.glb";
```
I will update our example, thank you for raising this.

**Comment by nforesperance** [comment]
Thanks alot. It works now!
