### ISSUE TITLE
onTapListener is there a way to make it trigger even when tapping on polygons?

### ISSUE THREAD

**Issue by UmidjonOkhunov** [mapbox/mapbox-maps-flutter#741]
We are trying to upgrade our mapbox from version 0.4.2 to the latest.

Our app performs certain actions when tapping on polygons and items inside the polygon. We also need to know the exact location of the tap.

However, the current behavior is it triggers the `onPolygonAnnotationClick`, but not `onTapListener`. 

Is there a way to trigger `onTapListener` every time regardless of what we tap on?

**Comment by evil159** [comment]
Hi @UmidjonOkhunov that behavior is not configurable at the moment, you can wrap map widget in a `GestureDetector` to receive tap events unconditionally, then you can use [`coordinateForPixel`](https://pub.dev/documentation/mapbox_maps_flutter/latest/mapbox_maps_flutter/MapboxMap/coordinateForPixel.html) method to convert the tap location into map coordinates.

**Comment by UmidjonOkhunov** [comment]
@evil159 thanks for the advice. For now, we decided to fork and change the source code to propagate the tap event, which works well with our use case.
