### ISSUE TITLE
Inheritance from non-protocol type 'any Error' with 2.4.0-beta.1 version

### ISSUE THREAD

**Issue by favazHF** [mapbox/mapbox-maps-flutter#745]
Good afternoon,

I have tried to compile my application on iOS pointing to the beta version (2.4.0-beta.1 ), to test with a certain percentage of users this fix -> (Fix a crash that occurs when the widget state is updated before the platform view is created. #724)

Will it be possible to do something? or do you know when the stable version will be released?

Best!

![image](https://github.com/user-attachments/assets/de24b52e-2043-433d-802b-786e953467c2)

**Comment by mauro-forest** [comment]
It would be great if you could add `#if hasFeature(RetroactiveAttribute)` for the @retroactive attribute to make it back compatible with older versions of Xcode (prior version 16).

**Comment by evil159** [comment]
Thank you for the report @favazHF and thank you @mauro-forest for the suggestion, I made the change in https://github.com/mapbox/mapbox-maps-flutter/pull/747

**Comment by evil159** [comment]
@favazHF releases have bi-weekly cadence, end of this week there should be an RC release, then two weeks after - stable release.
