### ISSUE TITLE
Add annotations from onCameraChangedListener

### ISSUE THREAD

**Issue by chrishibler** [mapbox/mapbox-maps-flutter#761]
I'm trying to add markers lazily as the user changes the map view. I debounce the onCameraChangedListener and get the markers for the new annotations. However, when adding them to the PointAnnotationManager, the new annotations don't show on the map. Any help would be appreciated. I've tried with using the same PointAnnotationManager I use on map load (which works in the load event) as well as creating a new PointAnnotationManager.

```
  Future<void> _onCameraChanged(CameraChangedEventData d) async {
    CameraState camera = await mapboxMap.getCameraState();
    final bounds = await mapboxMap.coordinateBoundsForCamera(CameraOptions(
      center: camera.center,
      zoom: camera.zoom,
      pitch: camera.pitch,
    ));
    Position ne = bounds.northeast.coordinates;
    Position sw = bounds.southwest.coordinates;

    Bounds apiBounds = Bounds(
      north: ne.lat as double,
      south: sw.lat as double,
      east: ne.lng as double,
      west: sw.lng as double,
    );

    // Load the image from assets
    final ByteData bytes = await rootBundle.load('assets/logo-sm.png');
    final Uint8List imageData = bytes.buffer.asUint8List();

    ResponsePage consPage = await Api().getUserConventionsByBounds(pageKey: 1, bounds: apiBounds);
    for (Convention c in consPage.conventions) {
      PointAnnotationOptions pointAnnotationOptions = PointAnnotationOptions(
          geometry: Point(coordinates: Position(c.position!.latitude, c.position!.longitude)),
          image: imageData,
          iconSize: 0.4);

      pointAnnotationManager.create(pointAnnotationOptions); // Same manager used in map load event
    }
```

**Comment by matthewtsmith** [comment]
@chrishibler I have almost your exact same setup and have been facing the same issue. However, I just realized that their `Position` class has the `lat,lng` params flipped from what I expected:

They have:
`Position(num lng, num lat, [num? alt])`

I was passing in `Position(lat,lng)`, which your code looks like it's doing as well, but the constructor takes lng, lat.

Now I'm seeing annotations show up on my map after adding them in my _onCameraUpdated call.

FYI, they have a `Position.named` constructor which makes constructing the Position a little more obvious.

**Comment by chrishibler** [comment]
> @chrishibler I have almost your exact same setup and have been facing the same issue. However, I just realized that their `Position` class has the `lat,lng` params flipped from what I expected:
> 
> They have: `Position(num lng, num lat, [num? alt])`
> 
> I was passing in `Position(lat,lng)`, which your code looks like it's doing as well, but the constructor takes lng, lat.
> 
> Now I'm seeing annotations show up on my map after adding them in my _onCameraUpdated call.
> 
> FYI, they have a `Position.named` constructor which makes constructing the Position a little more obvious.

Sir, you are a scholar and a gentleman. That was it. Thank you so much for your help!
