### ISSUE TITLE
pixelsForCoordinates not working as expected on iOS

### ISSUE THREAD

**Issue by leifhendrik** [mapbox/mapbox-maps-flutter#77]
When converting multiple latitudes/longitudes to screen coordinates with pixelsForCoordinates, on iOS, the function seems to return the latitude/longitudes that were used as input, rather than the pixel coordinates. On Android it works as expected.

Note that the similar function pixelForCoordinate works fine both on Android and iOS.

**Comment by yunikkk** [comment]
@leifhendrik hi, thanks for flagging, indeed it was mapped incorrectly

**Comment by leifhendrik** [comment]
Thank you!
