### ISSUE TITLE
Rotate globe automatically

### ISSUE THREAD

**Issue by hungcaovn** [mapbox/mapbox-maps-flutter#788]
I am not sure if we can rotate the globe automatically on map created? I tried to search but did not find any solutions. Thanks

**Comment by maios** [comment]
Hi @hungcaovn, I have created an example of spinning a globe by observing `CameraChanged` event and ease camera to the next camera position https://github.com/mapbox/mapbox-maps-flutter/pull/808
Please let me know if you have further question about this.
