### ISSUE TITLE
How to transition between different ViewportStates (OverviewViewportState -> FollowPuckViewportState)

### ISSUE THREAD

**Issue by vchrisb** [mapbox/mapbox-maps-flutter#807]
Happy to see Viewport support! 💯 

When creating a MapWidget initially with OverviewViewportState, how can I transition it to FollowPuckViewportState?
Similar to `mapView.viewport.transition(to: followPuckViewportState)` in Maps iOS SDK.

Thx!

**Comment by evil159** [comment]
Hi @vchrisb, thank for being the early adopter of the viewport API, we've implemented viewport in the declarative way for the map widget, change the viewport constructor parameter provided to the map widget inside a `setState(...)` call:
```dart
class SimpleMapExample extends StatefulWidget {
  const SimpleMapExample({super.key});

  @override
  State<StatefulWidget> createState() => _SimpleMapState();
}

class _SimpleMapState extends State<SimpleMapExample> {
  _SimpleMapState();
  bool _followUserLocation = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          MapWidget(
            styleUri: MapboxStyles.STANDARD,
            viewport: _followUserLocation
                ? FollowPuckViewportState()
                : CameraViewportState(
                    center:
                        Point(coordinates: Position(-117.918976, 33.812092)),
                    zoom: 15.0,
                  ),
          ),
          Positioned(
            bottom: 16.0,
            right: 16.0,
            child: FloatingActionButton(
              onPressed: () {
                setState(() {
                  _followUserLocation = !_followUserLocation;
                });
              },
              child: Icon(
                  _followUserLocation ? Icons.location_off : Icons.my_location),
            ),
          ),
        ],
      ),
    );
  }
}
```

Please note that there is a bug in 2.5.0-rc.1 viewport implementation on Android - attempting to interact with the map(i.e. touch/drag it) will result in an exception being thrown on the flutter side. We are going to address it in the upcoming 2.5.0 release.

**Comment by evil159** [comment]
We've introduced an experimental extension on widget: [`setStateWithViewportAnimation()`](https://pub.dev/documentation/mapbox_maps_flutter/2.5.0-rc.1/mapbox_maps_flutter/WidgetViewportAnimation/setStateWithViewportAnimation.html), use this to customize the transition between state changes.
Let me know about your experience using the viewport API and don't hesitate to send questions and/or feedback my way.

**Comment by vchrisb** [comment]
Thx! I'll give it a try.

**Comment by evil159** [comment]
@vchrisb easeTo() competes for camera state with the viewport(essentially they both are a series of setCamera() calls), if you want to change from following puck to looking at some particular point I suggest you to set the state to overview with the easing transition. In case your goal is to change the camera settings while following the puck I suggest to set a new follow puck state with updated settings(bearing, pitch etc.).

**Comment by vchrisb** [comment]
Thank you. Can you also comment on the first part?

> When I drag while FollowPuckViewportState is active, the follow puck does stop as desired. (I actually don't get an exception on android simulator)
> But how do I subscribe to this change? I would want to switch back to CameraViewportState() and style my button according

**Comment by evil159** [comment]
Good question, this is something that's not possible with the current implementation, we need to provide you with a callback about status being changed.

I've create a ticket to support this https://mapbox.atlassian.net/browse/MAPSFLT-282.
