### ISSUE TITLE
onLongTapListener returns Lat/Lng not real ScreenCoordinate

### ISSUE THREAD

**Issue by LorenzSchueler** [mapbox/mapbox-maps-flutter#81]
`onLongTapListener` returns a `ScreenCoordinate`, however the `x` and `y` values correspond to the lat/ lng of the position and not the coordinates on the screen (where 0, 0 is top left).

**Comment by evil159** [comment]
@LorenzSchueler Thank you for the report! I can confirm that this is a bug and we have it on our roadmap to fix it. Additionally we are considering reshaping that bit of API to report both screen and geographical coordinates of an interacted point.
