### ISSUE TITLE
Implemeting types to map.

### ISSUE THREAD

**Issue by RennanAgroSmart** [mapbox/mapbox-maps-flutter#87]
Hi i have many problems with the json params. I wonder if in future we will have class like params instead json parameters. Because i can help with this.

**Comment by sakyoyuto** [comment]
I agreed.
I am writing this kind of code now too.

```
static LatLng coordinatesToLatLng(Map<String?, Object?> center) {
    final lng = ((center['coordinates']! as List)[0] as double);
    final lat = ((center['coordinates']! as List)[1] as double);
    return LatLng(lat, lng);
  }

class LatLng {
  final double latitude;
  final double longitude;
  const LatLng(this.latitude, this.longitude);
}
```

**Comment by RennanAgroSmart** [comment]
Good!, i will open a PR to fix the parameter, to onTapListener. Because de ScreenCoordinate is a LatLng.
