### ISSUE TITLE
More customization options for ```CompassSettings()```.

### ISSUE THREAD

**Issue by Shiba-Kar** [mapbox/mapbox-maps-flutter#89]
How about adding ``size`` and ``color`` property !!

**Comment by LjubiTech-Maxko** [comment]
This plugin is using Mapbox v10.0.0 and there are no size and color properties in native implementations for [CompassSettings](https://docs.mapbox.com/android/maps/api/10.0.0/mapbox-maps-android/com.mapbox.maps.plugin.compass.generated/-compass-settings/), so there probably won't be in this plugin.
