### ISSUE TITLE
SymbolLayer does not have textField or textValue

### ISSUE THREAD

**Issue by festelo** [mapbox/mapbox-maps-flutter#91]
This problem was mentioned here - https://github.com/mapbox/mapbox-maps-flutter/issues/44, seems like author found workaround (thanks to him for this, it's very helpful) and closed the issue.

Although I think it's good idea to have textField as part of SymbolLayer, similar to what we have in [MapboxGl](https://pub.dev/documentation/mapbox_gl_platform_interface/latest/mapbox_gl_platform_interface/SymbolOptions-class.html)

**Comment by LjubiTech-Maxko** [comment]
@yunikkk Considering code for layers is generated it would be better to check the generation step that to open a pull request for this change? I checked all the layers properties and this is the only one that is missing.

**Comment by yunikkk** [comment]
> @yunikkk Considering code for layers is generated it would be better to check the generation step that to open a pull request for this change? I checked all the layers and their properties and this is the only one that is missing.

I'll take a look. The workaround using low-level `setStyleLayerProperties` should work until the properties are added.

**Comment by cturn-dev** [comment]
The workaround works perfectly fine on Android. However, on iOS, when we add the field: 'text-field': ['get', 'name'], no symbol is displayed anymore! When will the textField implementation be available?

**Comment by maios** [comment]
@festelo we have added support for [`SymbolLayer.textField`](https://github.com/mapbox/mapbox-maps-flutter/blob/main/lib/src/style/layer/symbol_layer.dart#L336) could you please try latest release [v2.2.1](https://pub.dev/packages/mapbox_maps_flutter)
