### ISSUE TITLE
Crashed when failed to load tile (OnMapLoadError)

### ISSUE THREAD

**Issue by ywjb** [mapbox/mapbox-maps-flutter#92]
E/Mapbox  (21385): [maps-android\Mbgl-StyleObserver]: OnMapLoadError: TILE, message: Failed to load tile: failed to connect to / xxx.xx from /xxxxx (port 36094) after 30000ms, sourceID: TEST, tileID: TileID(zoom=17, x=106863, y=56892)
D/AndroidRuntime(21385): Shutting down VM
E/AndroidRuntime(21385): FATAL EXCEPTION: main
E/AndroidRuntime(21385): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(21385): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
E/AndroidRuntime(21385): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler$1.reply(BasicMessageChannel.java:222)
E/AndroidRuntime(21385): 	at com.mapbox.maps.pigeons.FLTMapInterfaces$_MapInterface$1.error(FLTMapInterfaces.java:4070)
E/AndroidRuntime(21385): 	at com.mapbox.maps.mapbox_maps.MapInterfaceController$loadStyleURI$2.onMapLoadError(MapInterfaceController.kt:20)
E/AndroidRuntime(21385): 	at com.mapbox.maps.StyleObserver.onMapLoadError(StyleObserver.kt:113)
E/AndroidRuntime(21385): 	at com.mapbox.maps.NativeObserver.notify(NativeObserver.kt:52)
E/AndroidRuntime(21385): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(21385): 	at android.os.MessageQueue.next(MessageQueue.java:339)
E/AndroidRuntime(21385): 	at android.os.Looper.loopOnce(Looper.java:179)
E/AndroidRuntime(21385): 	at android.os.Looper.loop(Looper.java:344)
E/AndroidRuntime(21385): 	at android.app.ActivityThread.main(ActivityThread.java:8248)
E/AndroidRuntime(21385): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21385): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
E/AndroidRuntime(21385): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)

**Comment by Strafe0** [comment]
The same issue if there is no connection to internet.

**Comment by evil159** [comment]
Hi all! Thank you for reporting this, I took a jab at it but cannot get it to reproduce on the latest release `0.4.5`, when I subscribe to map load error event and make the map to error out(by enabling airplane mode) I receive the error events, but no exceptions.

Are there any specific steps to reproduce? A sample project replicating the issue would be much appreciated :)

**Comment by baleboy** [comment]
Closing as non-reproducible, please reopen if reproducible on 0.4.5 or later. Thank you!
