### ISSUE TITLE
How to make camera move to the user  location ? 

### ISSUE THREAD

**Issue by Shiba-Kar** [mapbox/mapbox-maps-flutter#98]

**Comment by yunikkk** [comment]
@Shiba-Kar this is duplicate with https://github.com/mapbox/mapbox-maps-flutter/issues/33 and will be available later with the Viewport API. 
Currently you can center the camera manually with `mapboxMap.setCamera` and e.g. get locations from location layer https://github.com/mapbox/mapbox-maps-flutter/blob/main/example/lib/utils.dart#L84
