### ISSUE TITLE
NullPointer dereference

### ISSUE THREAD

**Issue by LorenzSchueler** [mapbox/mapbox-maps-flutter#99]
Hi,
I'm currently encountering frequent null pointer dereferences, however they do not occur always. It seems like they are especially frequent when enabling terrain.

Flutter: `3.7.5` (stable)
mapbox-maps-flutter: `0.4.1`
<details>
<summary>Backtrace</summary>
<br>
<pre>
F/libc    (21548): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x20 in tid 21641 (MapboxRenderThr), pid 21548 (_log_client.dev)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
LineageOS Version: '20.0-20230216-NIGHTLY-chiron'
Build fingerprint: 'Xiaomi/chiron/chiron:8.0.0/OPR1.170623.027/V9.5.4.0.ODEMIFA:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2023-02-24 13:33:19.145558854+0100
Process uptime: 104s
Cmdline: org.sport_log.sport_log_client.dev
pid: 21548, tid: 21641, name: MapboxRenderThr  >>> org.sport_log.sport_log_client.dev <<<
uid: 10170
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000020
Cause: null pointer dereference
    x0  0000006df22d33a0  x1  0000006ca15fa200  x2  0000006ca15fa1e8  x3  0000006e022b3260
    x4  0000006c9040f2d4  x5  0000006ca15fa587  x6  000000006f6c7075  x7  0000000064616f6c
    x8  0000000000000000  x9  6508333cbe8ab926  x10 0000006d523c781c  x11 0000006ca15fa47c
    x12 6562616c2d746e65  x13 0000000000000010  x14 be41013c00000000  x15 6973697669646275
    x16 0000006c90758d10  x17 0000006fb2137820  x18 0000006ce1815120  x19 0000006d4232cad0
    x20 0000006e222c7270  x21 0000006d4234edd0  x22 0000000000000000  x23 0000006e222c73d0
    x24 0000006ca15fc000  x25 0000006e022b31d0  x26 0000000000000000  x27 00000000ffffffff
    x28 0000006e222c7270  x29 0000006ca15fa5c0
    lr  0000006c906cb218  sp  0000006ca15fa360  pc  0000006c906cb22c  pst 0000000020000000
backtrace:
      #00 pc 00000000004ca22c  /data/app/~~rkNiXAYtr3QI_Zwxkfiduw==/org.sport_log.sport_log_client.dev-EqlSk5CnsDIziuI0nuEWxg==/base.apk!libmapbox-maps.so (BuildId: f2318481d61c9bf6)
      #01 pc 0000000000388d60  /data/app/~~rkNiXAYtr3QI_Zwxkfiduw==/org.sport_log.sport_log_client.dev-EqlSk5CnsDIziuI0nuEWxg==/base.apk!libmapbox-maps.so (BuildId: f2318481d61c9bf6)
      #02 pc 000000000035cc54  /data/app/~~rkNiXAYtr3QI_Zwxkfiduw==/org.sport_log.sport_log_client.dev-EqlSk5CnsDIziuI0nuEWxg==/base.apk!libmapbox-maps.so (BuildId: f2318481d61c9bf6)
      #03 pc 000000000029eb18  /data/app/~~rkNiXAYtr3QI_Zwxkfiduw==/org.sport_log.sport_log_client.dev-EqlSk5CnsDIziuI0nuEWxg==/base.apk!libmapbox-maps.so (BuildId: f2318481d61c9bf6)
      #04 pc 000000000029acd8  /data/app/~~rkNiXAYtr3QI_Zwxkfiduw==/org.sport_log.sport_log_client.dev-EqlSk5CnsDIziuI0nuEWxg==/base.apk!libmapbox-maps.so (BuildId: f2318481d61c9bf6)
      #05 pc 000000000025ce7c  /data/app/~~rkNiXAYtr3QI_Zwxkfiduw==/org.sport_log.sport_log_client.dev-EqlSk5CnsDIziuI0nuEWxg==/base.apk!libmapbox-maps.so (BuildId: f2318481d61c9bf6)
      #06 pc 000000000021a354  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: 0c537e5efe426a30e9fde84241db9e3e)
      #07 pc 000000000020b120  /apex/com.android.art/lib64/libart.so (nterp_helper+7712) (BuildId: 0c537e5efe426a30e9fde84241db9e3e)
      #08 pc 0000000000331814  [anon:dalvik-classes.dex extracted in memory from /data/app/~~rkNiXAYtr3QI_Zwxkfiduw==/org.sport_log.sport_log_client.dev-EqlSk5CnsDIziuI0nuEWxg==/base.apk] (com.mapbox.maps.NativeMapImpl.render+4)
      #09 pc 000000000020b120  /apex/com.android.art/lib64/libart.so (nterp_helper+7712) (BuildId: 0c537e5efe426a30e9fde84241db9e3e)
      #10 pc 0000000000456c5e  [anon:dalvik-classes.dex extracted in memory from /data/app/~~rkNiXAYtr3QI_Zwxkfiduw==/org.sport_log.sport_log_client.dev-EqlSk5CnsDIziuI0nuEWxg==/base.apk] (com.mapbox.maps.renderer.MapboxRenderer.render+10)
      #11 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 0c537e5efe426a30e9fde84241db9e3e)
      #12 pc 0000000000455cea  [anon:dalvik-classes.dex extracted in memory from /data/app/~~rkNiXAYtr3QI_Zwxkfiduw==/org.sport_log.sport_log_client.dev-EqlSk5CnsDIziuI0nuEWxg==/base.apk] (com.mapbox.maps.renderer.MapboxRenderThread.draw+142)
      #13 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 0c537e5efe426a30e9fde84241db9e3e)
      #14 pc 0000000000455bc8  [anon:dalvik-classes.dex extracted in memory from /data/app/~~rkNiXAYtr3QI_Zwxkfiduw==/org.sport_log.sport_log_client.dev-EqlSk5CnsDIziuI0nuEWxg==/base.apk] (com.mapbox.maps.renderer.MapboxRenderThread.doFrame+20)
      #15 pc 000000000020b074  /apex/com.android.art/lib64/libart.so (nterp_helper+7540) (BuildId: 0c537e5efe426a30e9fde84241db9e3e)
      #16 pc 0000000000364e60  /system/framework/framework.jar (android.view.Choreographer$CallbackRecord.run+24)
      #17 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 0c537e5efe426a30e9fde84241db9e3e)
      #18 pc 0000000000364e30  /system/framework/framework.jar (android.view.Choreographer$CallbackRecord.run+40)
      #19 pc 0000000002012acc  /memfd:jit-cache (deleted) (android.view.Choreographer.doCallbacks+764)
      #20 pc 000000000200a564  /memfd:jit-cache (deleted) (android.view.Choreographer.doFrame+2228)
      #21 pc 000000000020a910  /apex/com.android.art/lib64/libart.so (nterp_helper+5648) (BuildId: 0c537e5efe426a30e9fde84241db9e3e)
      #22 pc 0000000000365196  /system/framework/framework.jar (android.view.Choreographer$FrameDisplayEventReceiver.run+22)
      #23 pc 000000000020b074  /apex/com.android.art/lib64/libart.so (nterp_helper+7540) (BuildId: 0c537e5efe426a30e9fde84241db9e3e)
      #24 pc 0000000000466fc4  /system/framework/framework.jar (android.os.Handler.handleCallback+4)
      #25 pc 0000000000209334  /apex/com.android.art/lib64/libart.so (nterp_helper+52) (BuildId: 0c537e5efe426a30e9fde84241db9e3e)
      #26 pc 0000000000466e18  /system/framework/framework.jar (android.os.Handler.dispatchMessage+8)
      #27 pc 000000000200bc20  /memfd:jit-cache (deleted) (android.os.Looper.loopOnce+1472)
      #28 pc 0000000000209a9c  /apex/com.android.art/lib64/libart.so (nterp_helper+1948) (BuildId: 0c537e5efe426a30e9fde84241db9e3e)
      #29 pc 0000000000489252  /system/framework/framework.jar (android.os.Looper.loop+162)
</pre>
</details>

**Comment by paulVulog** [comment]
Hi there, any Update on this ?
Looks like the mapbox version 2.0.0 bring back this specific issue on my side.
